### ISSUE TITLE
Enable code coverage for child processes

### ISSUE THREAD

**Issue by stevenvachon** [microsoft/node-pty#113]
My project's test suite had 100% code coverage when it was using `child_process.spawn`, but it's 0% now that it's switched to this library.

I'm guessing that because this library uses bindings to run the child process, coverage tools like [istanbul](https://npmjs.com/istanbul)/[nyc](https://npmjs.com/nyc) are incompatible. Is it possible to change that?

**Comment by Tyriar** [comment]
It would be possible to get a coverage report for the JS side, I'd want to convert all the tests to .ts https://github.com/Tyriar/node-pty/issues/114 and improve coverage before bothering with that right now.

Test coverage isn't the greatest atm but there are a [few](https://github.com/Tyriar/node-pty/blob/master/test/unixTerminal.test.js) [good](https://github.com/Tyriar/node-pty/blob/master/test/windowsTerminal.test.js) integration tests that go through a lot of the code to check the output of a command.

**Comment by stevenvachon** [comment]
Just to be sure that we're talking about the same thing, I'm talking about code coverage in my project which uses this library to perform its tests. While a code coverage badge for this repo would be nice, I want one on mine more 😉

**Comment by Tyriar** [comment]
Code coverage reports don't generally report on dependencies, won't that tell you that you just don't use a bunch of module code (which doesn't matter)?

For sure you can do it in yours, you just need to be careful to prevent flakiness because 1+ processes are going to be launched when you create a node-pty instance.

**Comment by stevenvachon** [comment]
I'm confused.

I have a `child.js` file that wraps [my project](https://npmjs.com/dotenv-prompt).

Before I was doing this and my coverage was reported to be 100%:
```js
child_process.spawn("node", ["child.js"]);
```

Now that I'm doing this, it reports 0% coverage:
```js
pty.spawn("node", ["child.js"]);
```

I'm not talking about covering this library's code in my project. I'm talking about getting code coverage for `child.js` and its local modules.

**Comment by Tyriar** [comment]
@stevenvachon how did it work with child_process.spawn? You're just running something in `node`, how does the coverage details get reported back?

**Comment by stevenvachon** [comment]
I don't know, but it did.

**Comment by Tyriar** [comment]
@stevenvachon that build is testing the commit https://github.com/stevenvachon/dotenv-prompt/commit/c893bb526bb8cb6f1b459e412eef73bbce943d0b which doesn't seem to be using `child_process.spawn`?

**Comment by jerch** [comment]
Just a wild guess (did not dig through the module code) - are they using the 'ipc' pipe mechanism nodejs provides for nodejs child processes? (see https://nodejs.org/api/child_process.html#child_process_options_stdio)
This is in theory pretty neat (can share serializable objects between the processes with JSON as "protocol"), not sure how useful it would be for pty.js as a general purpose pty lib.

**Comment by stevenvachon** [comment]
@Tyriar that commit is using `suppose` v0.6.2: https://github.com/stevenvachon/dotenv-prompt/blob/c893bb526bb8cb6f1b459e412eef73bbce943d0b/test.js#L61 ... which uses `child_process.spawn`, yes. My point is that it collected coverage information, where the currently unreleased version of [suppose] that uses this library *does not*.

**Comment by Tyriar** [comment]
@stevenvachon ah I misunderstood.

I don't really have time to look into this, if you figured out how the coverage reports are generated through `child_process.spawn` that could be helpful in determining whether something needs to happen within node-pty.

**Comment by emarcotte** [comment]
Depending on your needs, you may be able to get coverage reported using the wrap.js library from NYC. 

```
var pty = require('node-pty');

var ptyProc = pty.spawn('node', ['node_modules/nyc/bin/wrap.js', 'example.js'], {
        name: 'xterm-256color',
        cols: 80,
        rows: 30,
        cwd: __dirname,
        env: process.env,
});

ptyProc.on('data', function(data) {
        console.log("DEBUG", Buffer.from(data, 'utf-8'));
});

setTimeout( () => {
        ptyProc.kill();
}, 3000);

```
Which I was able to get to report coverage with a command like this:
```
[emarcotte@emarcotte-x1new node-ruis]$ npx nyc --show-process-tree node wrapper.js
DEBUG <Buffer 1b 5b 36 6e>
------------|----------|----------|----------|----------|-------------------|
File        |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
------------|----------|----------|----------|----------|-------------------|
All files   |    67.27 |    36.84 |    54.55 |    68.52 |                   |
 example.js |    63.27 |    36.84 |    44.44 |    64.58 |... 16,121,122,123 |
 wrapper.js |      100 |      100 |      100 |      100 |                   |
------------|----------|----------|----------|----------|-------------------|
nyc
└─┬ /usr/bin/node /home/emarcotte/Projects/node-ruis/wrapper.js
  │   68.52 % Lines
  └── /usr/bin/node /home/emarcotte/Projects/node-ruis/example.js
        64.58 % Lines

```
I haven't figured out how "official" this wrap.js path is though. Also not very transparent as you have to mod your tests/app to work with the coverage tool.
