### ISSUE TITLE
Make _fd and _pty public

### ISSUE THREAD

**Issue by hexa00** [microsoft/node-pty#143]
Hi,
   I use node-pty open() to open a pty and then use termios to set options on it.
 
   To use this termios needs an fd, however _fd is a protected property.

   I would also like to send the pty name to another program so I would need _pty to be public too.

Could these be made public ? Or could there by public accessors to them?

Thanks!

**Comment by Tyriar** [comment]
👍 to add public getters for them. I think renaming `pty` to `ptsName` would probably be best as I believe pts is most correct:

- https://linux.die.net/man/4/pts
- https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man4/pty.4.html

**Comment by marechal-p** [comment]
Bump! I would also be interested in having those fields public :)
