### ISSUE TITLE
Split node-pty into 2 components

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/node-pty#151]
I'm proposing we split node-pty into 2 sub-components that can be used independently or together with node-pty. The components would do:

1. Launch the shell and expose the FD (most of the C++ logic)
2. Connect to the FD (most of the TS logic)

This will help support:

- Reloading a VS Code window without terminating the shell processes https://github.com/Microsoft/vscode/issues/20013
- Not running native code on the Electron browser process to allow locking it down more in the future

Note that the node-pty repo and npm package will remain, nothing will change in that respect. The node-pty repo and package will mainly just be glue code between the new sub-components.

**Comment by jerch** [comment]
@Tyriar Sounds reasonable. All it needs on C++ side to keep ptys alive under Unix is the valid pty master fd (plus the emulator and buffer states to continue exactly where it stopped). Only the raw pty creation needs to be in component one, the shell could be spawned in TS land. No clue if such a separation would work with winpty.

**Comment by Tyriar** [comment]
No plans to do this any time soon
