### ISSUE TITLE
onExit callback should be typed to number

### ISSUE THREAD

**Issue by hexa00** [microsoft/node-pty#162]
https://github.com/Tyriar/node-pty/blob/e9c790871b55c8fe9920409f59fb12360adda999/src/unixTerminal.ts#L73

This line cast away the types returned by:

https://github.com/Tyriar/node-pty/blob/e9c790871b55c8fe9920409f59fb12360adda999/src/unix/pty.cc#L482

Thus if one tries:
```typescript
exitCallback (code, signal) {

  if (signal === '2') {
   // Do something
  }
}
```

The test will fail, note that one may get the impression that signal is a string since it is in nodejs API see: https://nodejs.org/dist/latest-v8.x/docs/api/child_process.html#child_process_event_exit

Typing the callback would avoid that issue I think.

**Comment by hexa00** [comment]
Actually maybe it won't fix the issue since the callback signature isn't carried though emit but it would give the right hint to a dev looking at the code...

**Comment by Tyriar** [comment]
I changed the code but you're right it will only give a hint when looking at the library code. What you want is possible by explicitly typing out the emit functions, but it will need the handwritten typing file to be done first https://github.com/Tyriar/node-pty/issues/154

**Comment by hexa00** [comment]
@Tyriar thx, nice I didn't know this was possible, looking forward to it  :)

**Comment by Tyriar** [comment]
It will end up looking something like this: https://github.com/xtermjs/xterm.js/blob/4f144dc6eb8bdb56dd4d705ca356694248ac2acc/typings/xterm.d.ts#L227

**Comment by hexa00** [comment]
Right, nice :)
