### ISSUE TITLE
Same code returns different results

### ISSUE THREAD

**Issue by mimarec** [Microsoft/node-pty#199]
The same code returns different results, depending on where the node application is run

## Details
- Browser and browser version:  Chrome Version 66.0.3359.181 (Build oficial) (64 bits)
- OS version: OS X El Capitan v10.11.6
- xterm.js version: 3.4.1
- node-pty: version 0.7.4

I'm having a behavior that I do not understand, the demo application opens with different information as you launch the process from one place or another:

1) Execute the npm start command from the command line (MacOSX Terminal) and the result obtained is as follows:

<img width="863" alt="captura de pantalla 2018-06-07 a las 11 27 02" src="https://user-images.githubusercontent.com/5499914/41091664-5f7c572c-6a47-11e8-87cd-e1c4aa656974.png">

2) Execute the command node app.js (MacOSX Terminal) over the demo folder and the result obtained is as follows:

<img width="991" alt="captura de pantalla 2018-06-07 a las 11 21 34" src="https://user-images.githubusercontent.com/5499914/41091673-66d078b4-6a47-11e8-9ecb-e0258f28e56d.png">

I don't understand, because the command `npm start` prints the name of the interpreter used, while the command `node app.js` prints my _user name_ '@' _name of the machine_ ':' _current working directory_.

PD: I am sure that this is not an issue but I not understanding the result.
PD2: Sorry for my English

**Comment by Tyriar** [comment]
See https://github.com/xtermjs/xterm.js/issues/1498
