### ISSUE TITLE
typings file missing in npm package

### ISSUE THREAD

**Issue by zijpn** [Microsoft/node-pty#205]
## Environment details

- OS: macos
- OS version: 10.13.5
- node-pty version: 0.7.5

## Issue description

Upgrading from 0.7.4 to 0.7.5 gave me 

> error TS7016: Could not find a declaration file for module 'node-pty'

I've noticed that the types were moved to a directory called _typings_.

As the package.json file specifies a files field, I suppose the typings directory needs to be added there as well. (https://docs.npmjs.com/files/package.json#files)

**Comment by Tyriar** [comment]
Doh, I'll look into it today. Thanks for the quick report!

**Comment by Tyriar** [comment]
Should be fixed now with 0.7.6
