### ISSUE TITLE
Can not link libpthread_nonshared.a in /usr/local/lib

### ISSUE THREAD

**Issue by gt945** [Microsoft/node-pty#209]
## Environment details

- OS: Chromeos + Chromebrew
- OS version: 67
- node-pty version:0.7.4

## Issue description
on chroneos with chromebrew, I only have libpthread_nonshared.a in /usr/local/lib.
but node-pty try to link to /usr/lib/libpthread_nonshared.a and the file is not exist.

After swap below two lines, link pass
https://github.com/Microsoft/node-pty/blob/2c1c0e78c8f110b4e3da87a3f9b88ebc9e7b33b8/binding.gyp#L31-L32

**Comment by JL2210** [comment]
Yeah... sorry, buddy. I don't think this is going to work, especially considering the fact that
1. Chrome OS is "unsupported" for VS Code
2. skycocker/chromebrew#3126 has been posted on the latest version of `code`.

**Comment by gt945** [comment]
@JL2210  this is work, I build vscode for chromebook plus before.
I think you patch the wrong file.
The correct file is located at cache dir in home
