### ISSUE TITLE
Support for running commands through the shell, like node's spawn

### ISSUE THREAD

**Issue by simark** [Microsoft/node-pty#229]
## Environment details

- OS: Ubuntu
- OS version: 16.04
- node-pty version: 0.7.6

## Issue description

With node's child_process.spawn, it's possible to run a command through the shell by passing the `shell: true` option.  Would it be possible to have node-pty do the same?  Is it not there by design, or just that no-one cared for it so far?

**Comment by jerch** [comment]
Have you tried? Imho it should always to do the environment/shell expansion, since it uses `execvp` internally. (See http://man7.org/linux/man-pages/man3/exec.3.html under "Special semantics for execlp() and execvp()").

**Comment by simark** [comment]
> Have you tried? Imho it should always to do the environment/shell expansion, since it uses `execvp` internally. (See http://man7.org/linux/man-pages/man3/exec.3.html under "Special semantics for execlp() and execvp()").

I guess you are referring to this sentence:

    The  execlp(),  execvp(), and execvpe() functions duplicate the actions of the shell in searching for an executable file if the specified filename does not contain a slash (/) character.

This is only does the "search in PATH" part that the shell does.  But the shell does more than that, including interpreting the command line and doing some expansions.  For example, you can give to the shell the string `ls *.jpg`.  It will first expand `*.jpg` according to the files in the current directory (e.g. `ls hello.jpg world.jpg`) and then split the full command line in a command and args (e.g. `"ls"` and `["hello.jpg", "world.jpg"]`).  These are not done by execvp and friends.

**Comment by jerch** [comment]
Ah yepp those things are not possible with it. Still a script would work.

And to answer your question above: guess noone really cared so far.

**Comment by Tyriar** [comment]
You can do this manually already right by configuring the process with `bash -c` or `cmd /k`?

**Comment by simark** [comment]
> You can do this manually already right by configuring the process with `bash -c` or `cmd /k`?

Yes it's probably enough to do that.  Having a `shell: true` option would fall in the nice to have category, so it's aligned with node's spawn and it is implemented once for everybody.

**Comment by Tyriar** [comment]
Thanks for the suggestion, closing as out of scope though since it's just a convenience thing.
