### ISSUE TITLE
Uncaught Error: Cannot find module "../build/Release/pty.node".

### ISSUE THREAD

**Issue by elmawardy** [Microsoft/node-pty#234]
## Environment details

- OS: Windows
- OS version: 10 Pro , Build : 17134.285
- node-pty version: 0.7.8

## Issue description

I've just installed **node-pty** with npm and bundled the "example usage" code from the repo README.md using webpack and I got this error in the browser :

Uncaught Error: Cannot find module "../build/Release/pty.node".

webpack conf :

```
let path = require('path');
let webpack = require('webpack');
// const UglifyJsPlugin = require('uglifyjs-webpack-plugin');
// var BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin;


const config = {

    entry: {
        'bundle':path.resolve(__dirname,'./index.js')
    },
    output:{
        path: path.resolve(__dirname,'./dist'),
        filename: '[name].js',
        publicPath: '/dist'
    },
    module:{
        rules:[
            {
                test: /\.js$/,
                loader: 'babel-loader'
            },
            { test: /\.json$/, loader: 'json-loader'},
            { test: /\.node$/, loader: 'file-loader'}
        ]
    },
    plugins:[
        require('babel-plugin-syntax-dynamic-import')
    ],
    node: {
        console: true,
        fs: 'empty',
        net: 'empty',
        tls: 'empty'
      }
}


module.exports = config
```

Thanks in advance!

**Comment by Tyriar** [comment]
That likely means it didn't build, check `npm i` for errors

**Comment by elmawardy** [comment]
@Tyriar thanks for reply , I ran `npm i` and this was the output :

```
npm WARN nodepty-test@1.0.0 No description
npm WARN nodepty-test@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

audited 6854 packages in 12.94s
found 2 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
```

**Comment by Tyriar** [comment]
Oh maybe this is webpack bundling node-pty's code? If so, that's not supported, you need to leave `./node_modules/node-pty` as is (exclude from bundling).

**Comment by elmawardy** [comment]
Wondering how to do that , I've excluded node-pty with externals in webpack like that :

```
externals: {
        "node-pty": "pty"
    },
```

however , obviously I got now "pty is not defined" in the browser because I haven't included any node-pty script in the html file , still confused which script should I include.

**Comment by Tyriar** [comment]
@elmawardy you cannot use node-pty in the browser, it needs to be run in a node context as it launches processes.

I recommend checking out https://github.com/Microsoft/node-pty/tree/master/examples/electron for an Electron example and https://github.com/xtermjs/xterm.js/tree/master/demo for a client/server example.

**Comment by elmawardy** [comment]
@Tyriar thanks :)

**Comment by ahkohd** [comment]
> Wondering how to do that , I've excluded node-pty with externals in webpack like that :
> 
> ```
> externals: {
>         "node-pty": "pty"
>     },
> ```
> however , obviously I got now "pty is not defined" in the browser because I haven't included any node-pty script in the html file , still confused which script should I include.

I too faced this same error @tyriar was right webpack is trying to load pty.node which is not meant to be bundled. I fixed this error using: https://www.npmjs.com/package/webpack-node-externals

```npm install webpack-node-externals --save-dev```
then in my webpack.config.js
```
.....
const nodeExternals = require('webpack-node-externals');
.....
{
.....
externals: [nodeExternals()]
.....
}
```

Tip:  After installing a native module like ```node-pty```, make sure you rebuild electron. See
https://github.com/electron/electron-rebuild

**Comment by fatso83** [comment]
A tip if you receive this while using PNPM. This is a bug in PNPM, which is not present in NPM: https://github.com/pnpm/pnpm/issues/2135

We got this when switching Node versions in a project. After that, no amount of `rm -r node_modules; pnpm i` would fix this issue. The `node-pty` dependency (included by `stmux`) always failed. It was only after doing `pnpm remove stmux && pnpm install stmux` the problem went away.
