### ISSUE TITLE
why it error on android?

### ISSUE THREAD

**Issue by huge818** [Microsoft/node-pty#235]
## Environment details

- OS: android
- OS version: 4.4.2
- node-pty version: node-pty@0.7.8

## Issue description
It error on android,
I use this project:
https://github.com/sjitech/build-nodejs-for-android

my main code is  server.js
===================================

const express = require('express');
const path = require('path');
const http = require('http');
const ws = require('ws');
const pty = require('node-pty');
const morgan = require('morgan');

const command = path.join(__dirname, 'run.sh');
const server = http.createServer();
const wss = new ws.Server({ server });
const app = express();

app.use(express.static(path.join(__dirname, 'public')));
app.use(morgan('dev'));

wss.on('connection', function (ws) {
	ws.on('error', () => {});
	const task = pty.spawn(command, [], {});
	task.on('data', data => {
		//console.log(222,data.toString());
		var str=data.toString().replace(/\\u001b\[0K/gi,"");
		str=str.replace(/\r/gi,"");
		str=str.replace(/\n/gi,"");
		ws.send(data);
	});
	ws.on('message', (msg) => {
		console.log(msg);
		task.write(msg);
	});
});

server.on('request', app);
server.listen(8081);
console.log("server.listen 8081");

==================================

1|root@astar-evb:/data/local/tmp/nodejs # ./bin/node ./android-ssh/server.js
int ttyname_r(int, char*, size_t)(3) is not implemented on Android
module.js:583
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: dlopen failed: empty/missing DT_HASH in "pty.node" (built with --hash-style=gnu?)
    at Error (native)
    at Object.Module._extensions..node (module.js:583:18)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/data/local/tmp/nodejs/android-ssh/node_modules/node-pty/lib/unixTerminal.js:21:11)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)

by th way ,I build the node-pty on arm-linux,not android system.

I copy the node_modules dir and other souce code  to android.

**Comment by Tyriar** [comment]
> int ttyname_r(int, char*, size_t)(3) is not implemented on Android

That's why. We don't support Android so it's not expected to work.
