### ISSUE TITLE
add support for "backpressure"

### ISSUE THREAD

**Issue by cs01** [Microsoft/node-pty#241]
## Issue description
In the case where the consumer of pty output cannot keep up, i.e.
```
ptyProcess.on('data', function(data) {
   // code here cannot keep up with speed of output
});
```

there is no way to indicate that the `ptyProcess` should slow down or stop reading output until the callback code has "caught up". Supporting a way to add this "backpressure" would be helpful.

See also https://www.reactivemanifesto.org/glossary#Back-Pressure

> When one component is struggling to keep-up, the system as a whole needs to respond in a sensible way. It is unacceptable for the component under stress to fail catastrophically or to drop messages in an uncontrolled fashion. Since it can’t cope and it can’t fail it should communicate the fact that it is under stress to upstream components and so get them to reduce the load. This back-pressure is an important feedback mechanism that allows systems to gracefully respond to load rather than collapse under it.

**Comment by jerch** [comment]
@cs01 How about `pipe / pause / resume`, not working for you?
You can also use XON/XOFF flow control with a pty, if you really need to tell the other side to stop sending stuff (not sure if this is working with win-pty).

**Comment by cs01** [comment]
This does what I'm looking for, thank you!
