### ISSUE TITLE
Supported operating systems

### ISSUE THREAD

**Issue by T-vK** [Microsoft/node-pty#250]
In the README it says that "Linux" is supported. Linux is essentially just a kernel which is used by many operating systems including Debian, RHEL and Android. 
In #79 however, it is says that Android is not supported. That begs the question if there are other Linux based operating systems that are not supported.

**Comment by jerch** [comment]
@T-vK For unixoid systems the module relies on the pty kernel interfaces + the userland libc (yes it also works on BSDs, Solaris and AIX, but its not officially supported).

As far as I am aware android misses several calls in their libc to successfully establish the pty connection. Android technically being a linux kernel does not help, they need provide those userland functions too. Thats the typical difference between linux seen as kernel only and linux seen as a kernel + userland env, the latter is the more common reception, even if technically wrong.
