### ISSUE TITLE
Unexpected whitespace with conpty

### ISSUE THREAD

**Issue by Meeeeow** [Microsoft/node-pty#254]
## Environment details

- OS: Windows 10
- OS version: 1809, 17763.195
- node-pty version: 0.8.0

## Issue description
See this screen capture, there are large space between lines, or unexpected wrap while no wraps in words
![conpty](https://user-images.githubusercontent.com/19658647/50629464-a24d2380-0f77-11e9-864c-3a3c7a50f9fe.gif)

## Code to reproduce
```js
var pty = require('node-pty');

var ptyProcess = pty.spawn('powershell.exe', [], {
  name: 'xterm-color',
  cols: 80,
  rows: 30,
  cwd: __dirname,
  env: process.env,
  experimentalUseConpty: true
});

ptyProcess.on('data', function(data) {
  console.log(data);
});

ptyProcess.write('ping /?\r');
```

**Comment by Tyriar** [comment]
It's because you're running console.log which adds a new line to the end

**Comment by Meeeeow** [comment]
@Tyriar It's the example in project readme.  as you say replace it with `process.stdout.write `resolved problem, but if i set `experimentalUseConpty: false` with `console.log` there is no extra new line in output.

BTW: It looks like `experimentalUseConpty` enabled by default in my new project

**Comment by Tyriar** [comment]
@Meeeeow 

> This might should be documented, or modify sample code in project readme

Good idea, do you want to put out a PR to get credit? FYI it will also happen when conpty is disabled, it's just conpty doesn't batch up sequences yet do there are many more individual messages.

> BTW: It looks like experimentalUseConpty enabled by default in my new project

Explained in the release notes, you can opt out if you want.

**Comment by Meeeeow** [comment]
@Tyriar PR #257
