### ISSUE TITLE
electron example not work on mac

### ISSUE THREAD

**Issue by jiangbo2015** [Microsoft/node-pty#258]
## Environment details

- OS: mac
- OS version:10
- node-pty version:0.7.4

## Issue description
first
```
npm install
```

second
```
npm start
```
![image](https://user-images.githubusercontent.com/14797518/50899963-97e6ca00-144e-11e9-94ba-9f581c4bab7d.png)

**Comment by Tyriar** [comment]
./npm_install.sh

https://github.com/Microsoft/node-pty/blob/master/examples/electron/README.md
