### ISSUE TITLE
duplicate writes to stdout on initial write

### ISSUE THREAD

**Issue by logicminds** [microsoft/node-pty#269]
## Environment details

- OS: OS X 
- OS version: 10.13
- node-pty version: 0.8.1

## Issue description

I recently switched from the older pty module of which this project was forked from and noticed some differences in terms of how writing to stdout and stdin are handled.

Previously I was using `processPty.stdin.write` to write data to the console. The cli app (processPty) would read from stdin, process it and then write to stdout. Because the app wrote to stdout the processPty.on('data') event would be triggered.

After switching to node-pty I had to refactor the code and use `processPty.write` instead. I am hoping that this change runs the exact same code as `processPty.stdin.write` used to.

However, my observations shows that `processPty.write` might be sending to stdin and stdout. Additionally, my cli app then writes to stdout as well. So I get double outputs to stdout.

Furthermore, this seems to only occur on the first `processPty.write` as subsequent writes do not exhibit this double stdout write behavior. Almost as if the initial echo to stdout happens before my cli app has completed initialization/loading (takes about 1500 ms to initialize).

You can view this intended and actual behavior in my apps below:

* [original working app](https://demo.puppet-debugger.com/play?content=vars)
* [refactored with node-pty app](https://puppet-debugger-stage.herokuapp.com/play?content=vars)

This problem looks to be the same as #180 and #78

**Comment by Tyriar** [comment]
Can you share the old/new server code?

**Comment by Tyriar** [comment]
AFAIK node-pty is behaving correctly by duplicating here, this is what other terminals do as well:

<img width="338" alt="screen shot 2019-02-21 at 2 00 54 pm" src="https://user-images.githubusercontent.com/2193314/53204709-29fef800-35e1-11e9-8118-60694d43dddf.png">

I don't know why you're not seeing it with pty.js but I'm interested. `term.stdin.write` should be the same as `term.write`:

https://github.com/chjj/pty.js/blob/fe63a412574f45ee6bb6d8fab4a5c102107b5201/lib/pty.js#L331-L337

**Comment by Tyriar** [comment]
Maybe this is why? https://github.com/chjj/pty.js/commit/ef6aa14981686daf869c0c05af326f84140fa97c
