### ISSUE TITLE
Feature request: event when terminal requests for password input and event when it ends

### ISSUE THREAD

**Issue by anandsiddharth** [Microsoft/node-pty#271]
## Environment details

- OS: Mac os
- OS version: 10.14.3
- node-pty version: 0.8.1

## Issue description

Whenever their is a password prompt in terminal, I would like to show popup for interactive password input using xterm.js and or input password programatically, I might be able to achive this by regex cheking "Password:" or "password:", but their can be multiple cases and this approach can trigger even if user is viewing a file or something. Is their a way where node-pty can emit event when password input is initialized.

**Comment by Tyriar** [comment]
AFAIK there's no way to do this other than scanning the text
