### ISSUE TITLE
24bit color support w/ conpty

### ISSUE THREAD

**Issue by lzybkr** [Microsoft/node-pty#272]
## Environment details

- OS: Windows
- OS version: 10.0.17763
- node-pty version: VSCode 1.31.1

## Issue description

My 24bit color prompt looks wrong. To reproduce with PowerShell:

```powershell
write-host "`n$([char]27)[1;38;2;15;90;13;48;2;230;110;0mHello $([char]27)[0mWorld`n"
```

In VS Code:

![image](https://user-images.githubusercontent.com/2148248/53849615-439f2880-3f6d-11e9-83e2-351fde848cc0.png)

In conhost:

![image](https://user-images.githubusercontent.com/2148248/53849629-4d289080-3f6d-11e9-8477-a6bcfde15b3b.png)

In alacritty (also using conpty):

![image](https://user-images.githubusercontent.com/2148248/53849637-57e32580-3f6d-11e9-805a-33524fed55d5.png)

**Comment by Tyriar** [comment]
VS Code doesn't support true color yet, see https://github.com/xtermjs/xterm.js/issues/484
