### ISSUE TITLE
node-pty can crash the process when ConPTY fails on Windows 32-bit

### ISSUE THREAD

**Issue by Tyriar** [microsoft/node-pty#277]
See https://github.com/Microsoft/console/issues/412

**Comment by Tyriar** [comment]
Something is going wrong with process creation when launching a sysnative shell

**Comment by DHowett-MSFT** [comment]
The ideal case is that _an application should not know about sysnative_. The proper way to launch a "native" shell from a WoW application is to disable filesystem redirection and use the real path (`C:\Windows\System32\xyz.exe`).

If VSCode has _disabled filesystem redirection_, `sysnative` will not exist.

**Comment by Tyriar** [comment]
I can't remember if this was the only reason, but PSReadLine doesn't work when running against System32 according to this comment:

https://github.com/Microsoft/vscode/blob/e4b5bccf9364a0f678606d5bdfc18800854bf678/src/vs/workbench/contrib/terminal/electron-browser/terminalService.ts#L123-L124

> If VSCode has disabled filesystem redirection, sysnative will not exist.

Isn't this only a problem if VS Code disables it, which it doesn't?

**Comment by dgriffen** [comment]
This is also affecting node-pty within visual studio since it ships the 32-bit version of node. Interestingly both `sysnative` and `System32` fail in this scenario.
