### ISSUE TITLE
"Could not fetch console process list" error log in console can happen when killing terminals on Windows

### ISSUE THREAD

**Issue by Tyriar** [microsoft/node-pty#278]
This log should be silent as we don't care when it happens:

https://github.com/Microsoft/node-pty/blob/ddc41d52de06936ef10475319c4c5cd9c28ce11d/src/windowsPtyAgent.ts#L178-L179

**Comment by coderaiser** [comment]
Looks like we can close this :) and to be in one step closer to `v0.9.0`.
