### ISSUE TITLE
implement 'off' or 'removeEventListener' for IPty

### ISSUE THREAD

**Issue by errorx666** [Microsoft/node-pty#281]
I'm using Webpack HMR to dynamically reload modules, and Rxjs `fromEventPattern` to subscribe to events.  When I change my code, my module gets reloaded, and the same IPty instance gets injected into the new module.

There doesn't seem to be any way to unsubscribe from events, so my module can't clean up after itself when it reloads.

**Comment by Tyriar** [comment]
Thanks for the report, closing in favor of https://github.com/Microsoft/node-pty/issues/282
