### ISSUE TITLE
Import winpty master

### ISSUE THREAD

**Issue by Eugeny** [microsoft/node-pty#296]
winpty master includes the fix for Ctrl-C behaviour in PowerShell, but they haven't released in two years. 

Would you consider importing the fresh winpty source into node-pty? It proved to be quite stable in Terminus, and I'm currently keeping a node-pty fork with the updated winpty inside

**Comment by Tyriar** [comment]
Sure, open to PRs, we just have a copy of the whole winpty project in deps atm. If you want to do this could you also include references to relevant changes/commits in the winpty project?
