### ISSUE TITLE
Using node-pty with child process spawn yields errors

### ISSUE THREAD

**Issue by jdshaeffer** [microsoft/node-pty#318]
## Environment details

- OS: macOS
- OS version: 10.14.5
- node-pty version: 0.8.1

## Issue description

I'd like to use node-pty as a way to pass a password so I can call an `ssh` command in my node.js app using child process spawn. I understand that node-pty is a fork of pty.js, which had a clear example of how to do this. I tried the same example using node-pty, but no dice. This is more a feature enhancement perhaps, but could you explain or offer an example on how that could be done? Thanks.

**Comment by Tyriar** [comment]
Yes this is possible to do, you spawn it then listen to `on('data')` for the password prompt, then call `pty.write('password')`.
