### ISSUE TITLE
OpenWRT/cross compilation issue

### ISSUE THREAD

**Issue by rgillan** [microsoft/node-pty#325]
## Environment details

- OS: OpenWRT
- OS version:18.06.01
- node-pty version:0.8.1

## Issue description
Trying to cross compile node-pty to run on OpenWRT on an aarch64 (cortexa53) processor, with the correct architecture OpenWRT SDK running on Ubuntu.  Other modules (e.g. websocket) with native code cross compile and run correctly.  When trying to run the cross compiled module on the target machine, we get:

module.js:549
    throw err;
    ^

Error: Cannot find module '../build/Debug/pty.node'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.loadNative (/usr/lib/node_modules/node-pty/lib/utils.js:22:16)
    at Object.<anonymous> (/usr/lib/node_modules/node-pty/lib/unixTerminal.js:24:19)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)

issue 256 here mentions it could be the error being mis-reported due to an incorrect architecture?  We are trying to compile to run on node 8.10.0 (same on both target and cross compile machine), npm 6.9.0 on both also.  This is the npm output from the install which only has a warning:

/opt/cc_aarch6_H5$ npm install node-pty --arch=aarch64

> node-pty@0.8.1 install /opt/cc_aarch6_H5/node_modules/node-pty
> node scripts/install.js

make: Entering directory `/opt/cc_aarch6_H5/node_modules/node-pty/build'
  CXX(target) Release/obj.target/pty/src/unix/pty.o
../src/unix/pty.cc: In function ‘void pty_after_waitpid(uv_async_t*)’:
../src/unix/pty.cc:489:69: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(v8::Local<v8::Object>, int, v8::Local<v8::Value>*) const’ is deprecated (declared at ../../nan/nan.h:1652) [-Wdeprecated-declarations]
   Nan::Callback(cb).Call(Nan::GetCurrentContext()->Global(), 2, argv);
                                                                     ^
  SOLINK_MODULE(target) Release/obj.target/pty.node
  COPY Release/pty.node
make: Leaving directory `/opt/cc_aarch6_H5/node_modules/node-pty/build'

> node-pty@0.8.1 postinstall /opt/cc_aarch6_H5/node_modules/node-pty
> node scripts/post-install.js

+ node-pty@0.8.1
removed 6 packages, updated 1 package and audited 2 packages in 2.093s
found 0 vulnerabilities

pty.node is compiled into build/Release.

Any help or suggestions gladly received.  We use node-pty elsewhere with great success and it's the last step to have our application run on OpenWRT.

Thanks /r

**Comment by Tyriar** [comment]
> Error: Cannot find module '../build/Debug/pty.node'

This normally means that it wasn't build, are you sure pty.node was in build/Release? It's pulled in here:

https://github.com/microsoft/node-pty/blob/04445ed76f90b4f56a190982ea2d4fcdd22a0ee7/src/unixTerminal.ts#L12-L17

If the file does exists I'm assuming something went wrong with the cross-compiling.

**Comment by rgillan** [comment]
Yep, made sure:

ls -l /usr/lib/node_modules/node-pty/build/Release/
-rw-r--r--    1 root     root         34588 Jun 21 00:03 pty.node

**Comment by Tyriar** [comment]
If you remove the try catch block in the compiled lib/unixTerminal.js what error does it give?

**Comment by rgillan** [comment]
if we comment out the try catch (in utils.js):

function loadNative(moduleName) {
//    try {
        return require(path.join('..', 'build', 'Release', moduleName + ".node"));
//    }
//    catch (_a) {
//        return require(path.join('..', 'build', 'Debug', moduleName + ".node"));
//    }
}

we get:

node iotransit-agent.js 
module.js:681
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Error relocating /usr/lib/node_modules/node-pty/build/Release/pty.node: unsupported relocation type 7
    at Object.Module._extensions..node (module.js:681:18)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.loadNative (/usr/lib/node_modules/node-pty/lib/utils.js:19:16)
    at Object.<anonymous> (/usr/lib/node_modules/node-pty/lib/unixTerminal.js:24:19)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
root@OpenWrt:

**Comment by rgillan** [comment]
Not sure if this helps, but this is the output of gcc -v on the compiler machine:
/opt/cc_aarch6_H5$ /opt/openwrt-sdk-18.06.2-sunxi-cortexa53_gcc-7.3.0_musl.Linux-x86_64/staging_dir/toolchain-aarch64_cortex-a53_gcc-7.3.0_musl/bin/aarch64-openwrt-linux-musl-g++ -v
Reading specs from /opt/openwrt-sdk-18.06.2-sunxi-cortexa53_gcc-7.3.0_musl.Linux-x86_64/staging_dir/toolchain-aarch64_cortex-a53_gcc-7.3.0_musl/bin/../lib/gcc/aarch64-openwrt-linux-musl/7.3.0/specs
COLLECT_GCC=/opt/openwrt-sdk-18.06.2-sunxi-cortexa53_gcc-7.3.0_musl.Linux-x86_64/staging_dir/toolchain-aarch64_cortex-a53_gcc-7.3.0_musl/bin/aarch64-openwrt-linux-musl-g++
COLLECT_LTO_WRAPPER=/opt/openwrt-sdk-18.06.2-sunxi-cortexa53_gcc-7.3.0_musl.Linux-x86_64/staging_dir/toolchain-aarch64_cortex-a53_gcc-7.3.0_musl/bin/../libexec/gcc/aarch64-openwrt-linux-musl/7.3.0/lto-wrapper
Target: aarch64-openwrt-linux-musl
Configured with: /build/openwrt-18.06/slaves/phase1/sunxi_cortexa53/build/build_dir/toolchain-aarch64_cortex-a53_gcc-7.3.0_musl/gcc-7.3.0/configure --with-bugurl=http://www.lede-project.org/bugs/ --with-pkgversion='OpenWrt GCC 7.3.0 r7627-753531d' --prefix=/build/openwrt-18.06/slaves/phase1/sunxi_cortexa53/build/staging_dir/toolchain-aarch64_cortex-a53_gcc-7.3.0_musl --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --target=aarch64-openwrt-linux-musl --with-gnu-ld --enable-target-optspace --disable-libgomp --disable-libmudflap --disable-multilib --disable-libmpx --disable-nls --without-isl --without-cloog --with-host-libstdcxx=-lstdc++ --with-gmp=/build/openwrt-18.06/slaves/phase1/sunxi_cortexa53/build/staging_dir/host --with-mpfr=/build/openwrt-18.06/slaves/phase1/sunxi_cortexa53/build/staging_dir/host --with-mpc=/build/openwrt-18.06/slaves/phase1/sunxi_cortexa53/build/staging_dir/host --disable-decimal-float --with-diagnostics-color=auto-if-env --disable-libssp --enable-__cxa_atexit --with-headers=/build/openwrt-18.06/slaves/phase1/sunxi_cortexa53/build/staging_dir/toolchain-aarch64_cortex-a53_gcc-7.3.0_musl/include --disable-libsanitizer --enable-languages=c,c++ --enable-shared --enable-threads --with-slibdir=/build/openwrt-18.06/slaves/phase1/sunxi_cortexa53/build/staging_dir/toolchain-aarch64_cortex-a53_gcc-7.3.0_musl/lib --enable-lto --with-libelf=/build/openwrt-18.06/slaves/phase1/sunxi_cortexa53/build/staging_dir/host
Thread model: posix
gcc version 7.3.0 (OpenWrt GCC 7.3.0 r7627-753531d)

**Comment by Tyriar** [comment]
Yeah it does look like something is going wrong with the cross compilation, I don't know so much in that area so if you can figure it out I'd be willing to accept a fix for it.

**Comment by rgillan** [comment]
Thanks, we'll keep digging and update.  Appreciate the responsiveness.

**Comment by rgillan** [comment]
Hi, so we've had the node-pty module cross compiled by the community (who's maintaining native node modules for OpenWRT).  This module is now successfully built and running in our environment.  The only trick we had to do was pass 'ash' as the shell (as OpenWRT BusyBox does not use bash by default).  Thanks for your help

**Comment by Tyriar** [comment]
Great to hear 😃
