### ISSUE TITLE
How to improve stdin write performance?

### ISSUE THREAD

**Issue by danepowell** [microsoft/node-pty#327]
## Environment details

- OS: Linux
- OS version: Ubuntu 19.04
- node-pty version: 0.8.1 / master (tried both)

## Issue description

I'm trying to replicate the following terminal command in node-pty: `mysql < db.sql`. In case you're not familiar, that should import a ~3MB SQL dump (text file) via mysql.

I'm using node-pty something like this (abbreviated quite a bit):
```js
const sql = fs.readFileSync('db.sql', 'ascii')
const proc = pty.spawn('mysql')
proc.write(sql.toString() + '\rexit\r')
```

This doesn't work as expected though. The first dozen or so tables get created, but then the process just hangs and never finishes. If I echo stdout, I see that it is doing something, it just looks like it's doing it one character at a time or something.

I have a few questions. First and foremost, what would be the best way to get this working, or at least to troubleshoot? Is there a standard/better way provide stdin from a file like that?

Secondly, why does node-pty behave so differently from a normal shell when handling stdin, in the sense that I don't have to worry about escaping input when running `mysql < db.sql` via the CLI, nor do I have to send specific control sequences like `\rexit\r`? If you just run `mysql` on its own, it will open a console, and it seems like node-pty is essentially doing this prior to sending writing stdin, rather than doing whatever normally happens via stdin redirection on the shell.

**Comment by Tyriar** [comment]
Does this work better?

```
const proc = pty.spawn('sh', ['-c', 'mysql < db.sql');
```

**Comment by danepowell** [comment]
That totally does work! Good idea.

I still don't understand why spawning it without sh behaves subtly differently from doing it via the terminal. That's more of a reflection of my lack of understanding than an indication of a problem with node-pty :smile: I would like to understand though.

I also narrowed down the cause of the performance problems. It was due to binary elements in the SQL dump. Any time one of those hit stdin cpu usage hit 100% and the process slowed to a crawl. I worked around this by using `SOURCE db.sql;` instead of streaming the entire file via stdin.

Like I said, I'd still like to understand how this could have gone better, but since I've figured out a good (or even better) workaround, feel free to close this.

**Comment by Tyriar** [comment]
> I still don't understand why spawning it without sh behaves subtly differently from doing it via the terminal. That's more of a reflection of my lack of understanding than an indication of a problem with node-pty 😄 I would like to understand though.

I don't know much about why you would want to run something like mysql in a pty. if you launch it with a shell, that's basically what a terminal would be working with.
