### ISSUE TITLE
^0.9.0-beta picks up older version

### ISSUE THREAD

**Issue by creatorrr** [microsoft/node-pty#328]
## Environment details

- OS: Ubuntu
- OS version: 19.04
- node-pty version: ^0.9.0-beta

## Issue description

Not sure if I am doing something wrong but specifying `^0.9.0-beta` picks up `0.9.0-beta9` instead of `0.9.0-beta18` (latest at the time of writing). From what I understood from the [docs](https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004), it should pick up the latest.

For a possibly relevant discussion, see: https://github.com/runvnc/babel-changed/pull/4#issuecomment-508608379

**Comment by Tyriar** [comment]
Works for me, the latest version for the beta tag is beta19: https://www.npmjs.com/package/node-pty
