### ISSUE TITLE
Migrate from GYP to GN

### ISSUE THREAD

**Issue by ioquatix** [microsoft/node-pty#330]
We have a ton of issues in `script-runner` because of `node-pty` build failing due to node-gyp not being compatible with python3.

e.g. https://github.com/ioquatix/script-runner/issues/103

It looks like the latest version of Electron moved to GN: https://electronjs.org/blog/gn

Maybe it would be a good idea for this project.

**Comment by Tyriar** [comment]
@deepak1556 has node moved to GN?

**Comment by deepak1556** [comment]
Nope and they don't plan to do that anytime soon https://github.com/nodejs/node/issues/21410, https://github.com/nodejs/TSC/issues/648 , https://github.com/nodejs/TSC/issues/642

Here is some discussion about getting python3 support in node-gyp https://github.com/nodejs/node-gyp/issues/1337 and there are workarounds mentioned in that thread.

I would recommend not to change the build system, its more technical debt when the adoption rate is nearly zero in the community. But some modules rely on https://github.com/cmake-js/cmake-js which is looked as an alternative.

**Comment by ioquatix** [comment]
That all makes sense. I'm sorry I didn't know more. We've just had a hell of a time with gyp and python2.7 especially with `Atom.io` and it's weird python wrappers.

**Comment by Tyriar** [comment]
I don't think we should until node has adopted it, https://github.com/microsoft/node-pty/issues/46 is the real problem you're having @ioquatix
