### ISSUE TITLE
Build Failure on Mac against Electron headers

### ISSUE THREAD

**Issue by pfitzseb** [microsoft/node-pty#335]
## Environment details

- OS: macOS
- OS version: 10.13
- node-pty version: master

## Issue description
While trying to create prebuilt binaries for this ([node-pty-prebuilt](https://github.com/daviwil/node-pty-prebuilt) doesn't ship binaries for newer node versions on all OSs), I'm encountering the following error when trying to build with Electron headers:
```
  CXX(target) Release/obj.target/pty/src/unix/pty.o
../src/unix/pty.cc:635:10: error: use of undeclared identifier 'openpty'
  return openpty(amaster, aslave, name, (termios *)termp, (winsize *)winp);
         ^
../src/unix/pty.cc:684:10: error: use of undeclared identifier 'forkpty'
  return forkpty(amaster, name, (termios *)termp, (winsize *)winp);
         ^
2 errors generated.
```
See e.g. [here](https://dev.azure.com/pfitzseb/node-pty-prebuilt/_build/results?buildId=29) for logs.
I kinda suspect something like [this](https://github.com/microsoft/node-pty/commit/5db10ca4e3970a65492ee0bb7c1f02766d7d6628) happening, where the build picks up the wrong `utils.h` and therefore can't find `openpty`/`forkpty`, but weirdly enough the prebuild against Node headers goes through fine.

It's fairly difficult for me to debug this since I don't have immediate access to a MacOS machine, so any help would be appreciated.

---

Kinda unrelated, but the `Cannot find module '../build/Debug/pty.node'` that were popping up occasionally seem to be caused by building against the wrong headers or something like that, since that `try-catch` statement will hide e.g. 
``` 
Uncaught Error: A dynamic link library (DLL) initialization routine failed.
\\?\C:\Users\...\.atom\packages\julia-client\node_modules\node-pty-prebuilt\build\Release\conpty.node
```

**Comment by Tyriar** [comment]
The logs say you're building against node 5? We only support 8+ https://github.com/microsoft/node-pty/issues/320 

> prebuild info build Preparing to prebuild @pfitzseb/node-pty-prebuilt@0.9.0-alpha7 for node 5.0.0 on darwin-x64 using node-gyp

**Comment by pfitzseb** [comment]
Sorry for getting back to this so late, but I had a mostly working solution until yesterday.

This is an excerpt of the log I was referring to:
```
npx prebuild -t 3.0.0 -t 4.0.0 -t 4.0.4 -t 5.0.0 -r electron -u $GITHUB_RELEASE_TOKEN
========================== Starting Command Output ===========================
[command]/bin/bash --noprofile --norc /Users/vsts/agent/2.155.1/work/_temp/87bf320f-a302-4af4-9c3f-b594145803ae.sh
prebuild info begin Prebuild version 9.0.1
prebuild info build Preparing to prebuild node-pty-binaries@0.9.0-prebuilt3 for electron 3.0.0 on darwin-x64 using node-gyp
prebuild http GET https://atom.io/download/electron/v3.0.0/iojs-v3.0.0-headers.tar.gz
prebuild http 200 https://atom.io/download/electron/v3.0.0/iojs-v3.0.0-headers.tar.gz
prebuild http GET https://atom.io/download/electron/v3.0.0/SHASUMS256.txt
prebuild http 200 https://atom.io/download/electron/v3.0.0/SHASUMS256.txt
prebuild info spawn /usr/local/bin/python2
prebuild info spawn args [ '/Users/vsts/agent/2.155.1/work/1/s/node_modules/node-gyp/gyp/gyp_main.py',
prebuild info spawn args   'binding.gyp',
prebuild info spawn args   '-f',
prebuild info spawn args   'make',
prebuild info spawn args   '-I',
prebuild info spawn args   '/Users/vsts/agent/2.155.1/work/1/s/build/config.gypi',
prebuild info spawn args   '-I',
prebuild info spawn args   '/Users/vsts/agent/2.155.1/work/1/s/node_modules/node-gyp/addon.gypi',
prebuild info spawn args   '-I',
prebuild info spawn args   '/Users/vsts/.node-gyp/iojs-3.0.0/common.gypi',
prebuild info spawn args   '-Dlibrary=shared_library',
prebuild info spawn args   '-Dvisibility=default',
prebuild info spawn args   '-Dnode_root_dir=/Users/vsts/.node-gyp/iojs-3.0.0',
prebuild info spawn args   '-Dnode_gyp_dir=/Users/vsts/agent/2.155.1/work/1/s/node_modules/node-gyp',
prebuild info spawn args   '-Dnode_lib_file=/Users/vsts/.node-gyp/iojs-3.0.0/<(target_arch)/iojs.lib',
prebuild info spawn args   '-Dmodule_root_dir=/Users/vsts/agent/2.155.1/work/1/s',
prebuild info spawn args   '-Dnode_engine=v8',
prebuild info spawn args   '--depth=.',
prebuild info spawn args   '--no-parallel',
prebuild info spawn args   '--generator-output',
prebuild info spawn args   'build',
prebuild info spawn args   '-Goutput_dir=.' ]
prebuild info spawn make
prebuild info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/pty/src/unix/pty.o
../src/unix/pty.cc:635:10: error: use of undeclared identifier 'openpty'
  return openpty(amaster, aslave, name, (termios *)termp, (winsize *)winp);
         ^
../src/unix/pty.cc:684:10: error: use of undeclared identifier 'forkpty'
  return forkpty(amaster, name, (termios *)termp, (winsize *)winp);
         ^
2 errors generated.
```
from [here](https://dev.azure.com/pfitzseb/node-pty-binaries/_build/results?buildId=45) (under MacOS_Electron) -- apparently it's not possible to link against a specific log file on Azure Devops. The build should also be running with Node 10 (see [here](https://github.com/pfitzseb/node-pty-binaries/blob/15bc24660cfa70d5eb4c8896d44d5046b6a97b89/azure-pipelines.yml#L41-L56)).

I have no idea if this is specific to the CI env or `prebuild` though.

**Comment by akarsh42** [comment]
is this sloved ??
