### ISSUE TITLE
Build failure on platforms with libdir != /usr/lib

### ISSUE THREAD

**Issue by xen0n** [microsoft/node-pty#338]
## Environment details

- OS: Linux/MIPS
- OS version: 5.2
- node-pty version: `master` branch

## Issue description

On platforms with libdir != `/usr/lib`, the native binding compilation obviously fails (in this case n64 MIPS where libdir = `/usr/lib64`):

```
/usr/lib/gcc/mips64el-unknown-linux-gnu/9.1.0/../../../../mips64el-unknown-linux-gnu/bin/ld: /usr/lib/libutil.so: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status
```

Is there any reason the libdir must be hard-coded in `binding.gyp`, as `libutil.so` should always reside in the default libdir whose location the platform `cc` definitely knows about?

**Comment by Tyriar** [comment]
@deepak1556 should we just add /usr/lib64 to the list here?

https://github.com/microsoft/node-pty/blob/7bd4c73db47f37f10706defd00c6557bc7020d13/binding.gyp#L59-L60

**Comment by xen0n** [comment]
Out of curiosity, why can't the library paths simply be removed? I just removed the two arguments and the build was fixed.

**Comment by deepak1556** [comment]
@xen0n is correct, we don't need to specify the default user library paths, it will be picked up by the build system not something gyp should worry about. Explicit path specifications are only necessary when the library is in some custom location, or we need to modify rpaths.
