### ISSUE TITLE
Error using node-pty dependency

### ISSUE THREAD

**Issue by mozgbrasil** [microsoft/node-pty#345]
Hello

Good Morning

I am having the problem in the following issue, if you can help in advance thank you

https://github.com/rekit/rekit-studio/issues/3

**Comment by Tyriar** [comment]
Looks like it's probably compiling against the wrong version fo node or something, normally these sorts of issues are handled by instructions from the application about dependencies you need, or the application supplies a precompiled version of node-pty.
