### ISSUE TITLE
Any way to get error code?

### ISSUE THREAD

**Issue by ZedYeung** [microsoft/node-pty#346]
## Environment details

- OS:
- OS version:
- node-pty version:

## Issue description
e.g. 
```
ls n
ls: cannot access 'n': No such file or directory
```

```
echo $?
2
```
Any way I could get the return code so that I could know whether the command success or fail without running this `echo $?`

**Comment by jerch** [comment]
@ZedYeung Nope, thats not possible in a platform independent way. The returnCode of a process is typically only reported to the parent process with a wait command and does not bubble further. In your example the shell knows it as it is the parent process of the failing command. Unless the shell has a sideway to report this you are out of luck.

But as you already figured you could work around that problem by exiting the shell with the returnCode of the sub process (e.g. in bash shell):
```
ls n
ls: cannot access 'n': No such file or directory
exit $?
```

and grab it with:
```typescript
pty.on('exit', (code: number, signal: number) => console.log('return code was:', code));
```
