### ISSUE TITLE
Error: cannot find module '..\build\debug\conpty.node'

### ISSUE THREAD

**Issue by ismaeelakram** [microsoft/node-pty#348]
## Environment details

- OS: Windows 10
- OS version: 1903
- node-pty version: 0.8.1

## Issue description
When I try to spawn a shell, I get an error saying that it cannot find module '..\build\debug\conpty.node'

Here's a screenshot of the error code:
![image](https://user-images.githubusercontent.com/19865145/64066404-2038fb80-cbe7-11e9-9e48-f3f1e2cab9f6.png)

**Comment by Tyriar** [comment]
Please try again using either the upcoming release or `node-pty@0.9.0-beta25`

After https://github.com/microsoft/node-pty/pull/340 the error provided should point you in the right direction.

**Comment by Jangyaseni666** [comment]
any updates on this? Like did u solve the problem??
