### ISSUE TITLE
why can not call the image process in macos?

### ISSUE THREAD

**Issue by hanzhibang001** [microsoft/node-pty#349]
## Environment details

- OS: Mac
- OS version: 10.14.5
- node-pty version: 0.8.1
## Issue description
run the python code about showing image,but in macos,it can not call the image process,why?

I try this code in different os verison, it also fail. but this code run successful in the node child_process module!

the following is the python code
```python
import qrcode
text = "this is a text"
img = qrcode.make(text)
img.show()
```
please give a solution,thanks a lot!

**Comment by ismaeelakram** [comment]
I'm not a node-pty expert but:
1. This is an entire other language.
2. What does QR code have to do with node-pty?

**Comment by hanzhibang001** [comment]
I know what is happen, beause the main process is done and it will kill all sub process. the macos preview is the sub process belong to node-pty.

**Comment by hanzhibang001** [comment]
I know what is happen, beause the main process is done and it will kill all sub process. the macos preview is the sub process belong to node-pty.
