### ISSUE TITLE
Not able to get node-pty working with Node 12 and Electron 6

### ISSUE THREAD

**Issue by rolanday** [microsoft/node-pty#352]
## Environment details

- OS: macOS
- OS version: Mojave
- node-pty version: 0.9.0-beta26
- Node 12.0

## Issue description
Builds, but loader complains version mismatch when attempting to load node.pty. No luck with electron-rebuild, or the usual troubleshoot steps such as deleting node-modules and reinstalling, npm rebuild, etc. If revert same project back to node 10 LTS and Electron 4 all is well again.

**Comment by Tyriar** [comment]
It definitely works as VS Code is on Electron 6 building with [Node.JS, x64, version >= 10.16.0, < 11.0.0](https://github.com/Microsoft/vscode/wiki/How-to-Contribute#prerequisites), we've been shipping Insiders for weeks on Electron 6 and node-pty-beta19. I just updated it to beta26 and it seems to work fine too.

So it seems like it's an issue with your build system, ping me if you find out more though.

**Comment by rolanday** [comment]
Thanks for getting back as forced me to take another look -- sometimes knowing it should work is all it takes :-) The issue was my IDE config pointing to an electron instance in a different project. All appears to be well with latest node-pty beta working with node v12 and electron 6.

**Comment by Tyriar** [comment]
Great! 😃
