### ISSUE TITLE
Duplicated output in console

### ISSUE THREAD

**Issue by jaulz** [microsoft/node-pty#354]
## Environment details

- OS: macOS
- OS version: 10.14.6
- node-pty version: ^0.9.0-beta26

## Issue description

When I try to set up a simple command line it basically works fine but when I enter commands the input line `root@3275dc3bdabb:/#` is always duplicated. Is there an issue with my code and am I mixing up something with the stdin and stdout?

```ts
  const path = 'docker exec -it 3275dc3bdabb bash'

  // Create PTY
  const shell = os.platform() === 'win32' ? 'powershell.exe' : 'bash'
  const ptyProcess = spawn(shell, [], {
    name: 'xterm-color',
  })

  // Send command
  ptyProcess.write(`${path}\n`)

  // Send input from terminal to PTY
  process.stdin.on('data', (data: string) => {
    ptyProcess.write(`${data}\n`)
  })

  // Get output of PTY
  ptyProcess.on('data', function(data) {
    process.stdout.write(data)
  })
```

The output is the following:
````
docker exec -it 3275dc3bdabb bash
bash-3.2$ docker exec -it 3275dc3bdabb bash
root@3275dc3bdabb:/# ls
ls
bin   dev  home  lib64  mnt  proc  root  sbin  sys  usr
boot  etc  lib   media  opt  ps    run   srv   tmp  var
root@3275dc3bdabb:/# 
root@3275dc3bdabb:/# ls
ls
bin   dev  home  lib64  mnt  proc  root  sbin  sys  usr
boot  etc  lib   media  opt  ps    run   srv   tmp  var
root@3275dc3bdabb:/# 
root@3275dc3bdabb:/# 
````

**Comment by Tyriar** [comment]
I think there's an issue with how you're printing to the console, things are definitely not repeated when hooked up correctly. Here's how the electron example does it and it works fine:

https://github.com/microsoft/node-pty/blob/d15af01803ea46e2d2585e23cbd2cfb9f096c6a0/examples/electron/renderer.js#L19-L23

**Comment by jaulz** [comment]
@Tyriar hm, but that's something different because the output is in DOM isn't it?

**Comment by Tyriar** [comment]
@jaulz yes but that proved the problem is on your end, I haven't tried doing a console-based terminal with node-pty.

**Comment by rvignesh123** [comment]
You have to ensure the Xterm Terminal size ie. rows and cols are set equal with PtyProc.rows and cols ..
So render will work fine without duplicating I think.

Use a resize function for the terminal and set it to the PtyProc object.

`  ptyProc.resize(
    Math.max(size ? size.cols : term.cols, 1),
    Math.max(size ? size.rows : term.rows, 1)
  );`
