### ISSUE TITLE
Run get proc name function in another thread

### ISSUE THREAD

**Issue by Tyriar** [microsoft/node-pty#356]
VS Code issue: https://github.com/microsoft/vscode/issues/75145

PtyGetProc is run in the same thread and it can block the UI:

https://github.com/microsoft/node-pty/blob/32ea3e47791794a82c58c76bf83dc4d441a93108/src/unix/pty.cc#L372-L395

**Comment by HsunGong** [comment]
Suggestion: Have a `Show More` Button on the big folder, and be able to show the number of files

**Comment by HsunGong** [comment]
Care about this issue.
https://github.com/microsoft/node-pty/blob/32ea3e47791794a82c58c76bf83dc4d441a93108/src/unix/pty.cc#L394
For this line, can we add a condition like 
```
if (name_.size() > 100) {
    name_ = name_.substr(100);
}
```
and `100` can be modified in `user settings`

**Comment by Tyriar** [comment]
@HsunGong wouldn't it be `pty_getproc` that's causing the problem? Not the size of `name_`?
