### ISSUE TITLE
Error: Cannot find module '..\build\Debug\pty.node'

### ISSUE THREAD

**Issue by roguexiaohuihui** [microsoft/node-pty#360]
## Environment details

- OS:  Windows
- OS version:  Windows 10
- node-pty version: ^0.8.1

## Issue description
develop the VSCODE plug-in，want to use node-pty to implement a function.

![image](https://user-images.githubusercontent.com/22930711/67255722-1c727880-f4b6-11e9-8a78-698f76aa4ea2.png)

![image](https://user-images.githubusercontent.com/22930711/67255648-b4239700-f4b5-11e9-96c9-e959c1e35772.png)

**Comment by Tyriar** [comment]
You can try install a beta to see what the issue is, a better error message should appear then. Note that node-pty is a native node module which are complex to ship within vscode extensions though, you will need to either ship the native binaries for all platforms with the extension or dynamically download them.

**Comment by roguexiaohuihui** [comment]
![image](https://user-images.githubusercontent.com/22930711/67347050-8a30aa00-f573-11e9-9e82-d6fccad7b7df.png)

was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 69. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).

**Comment by roguexiaohuihui** [comment]
> You can try install a beta to see what the issue is, a better error message should appear then. Note that node-pty is a native node module which are complex to ship within vscode extensions though, you will need to either ship the native binaries for all platforms with the extension or dynamically download them.

I tried 0.9.0-beta19, but the results were the same，

**Comment by roguexiaohuihui** [comment]
> You can try install a beta to see what the issue is, a better error message should appear then. Note that node-pty is a native node module which are complex to ship within vscode extensions though, you will need to either ship the native binaries for all platforms with the extension or dynamically download them.

I tried 0.9.0-beta19, but the results were the same.

In the vscode plug-in, I simply introduced the node-pty module and then called spawn and it went wrong.

I don't know if it is related to the plug-in running environment. Could you please help me

**Comment by Tyriar** [comment]
This is another problem with native node modules in VS Code extensions, you shouldn't use node-pty there as it would be a maintenance nightmare and your extension would break whenever we update Electron
