### ISSUE TITLE
node-pty not compatible with electron when asar is used, due to winpty.dll dependency

### ISSUE THREAD

**Issue by Marcus10110** [microsoft/node-pty#372]
## Environment details

- OS: Windows
- OS version: Windows 10 x64, regular install (build 17763)
- node-pty version: 0.9.0

Electron 7.1 via electron-forge
node 12.13 installed.

electron forge config has `asar: true` which causes the output application to use app.asar to hold the required files, including node_modules and node-pty.

## Issue description

Error occurs when trying to use node-pty.

Specifically, node-pty fails when trying to require `pty.node` here:
https://github.com/microsoft/node-pty/blob/f3099ad49177197203b27e9450aef7c03530c375/src/windowsPtyAgent.ts#L77

Inside of require, the following things happen:
1. the path is computed to be: "C:\Users\Mark\Software\monorepo\packages\electron\out\Logic-win32-x64\resources\app.asar\node_modules\node-pty\build\Release\pty.node"
2. the path is checked to see if it is in an asar. It is.
3. pty.node is extracted from the asar file and saved in "C:\Users\Mark\AppData\Local\Temp\018313d6-b4f6-4b9b-b99d-dde9bcb0e0e8.tmp.node"
4. this code is run: `process.dlopen(module, "C:\Users\Mark\AppData\Local\Temp\018313d6-b4f6-4b9b-b99d-dde9bcb0e0e8.tmp.node")`
5. The error "The specified module could not be found" is thrown.

**Specifically, the module that cannot be found is winpty.dll. If you copy winpty.dll into the same Temp directory, everything works fine.**

Note: With the windows insider build, this does not happen. That's because the insider build is 19025, and this code checks that and switches to conpty:
https://github.com/microsoft/node-pty/blob/f3099ad49177197203b27e9450aef7c03530c375/src/windowsPtyAgent.ts#L58

conpty.node does not depend on winpty.dll, and so that loads out of the box. If `useConpty` is set to false in `pty.spawn`, then the same failure occurs on the insider build.

We've been shipping our application using asar for a while, but we're going to try disabling it in the near term. **I think a simple solution might be to simply statically link winpty so it can be linked into pty.node, which would bypass the problem.**

Screenshot of the exception. (loading this module from an electron render process with node integration enabled)
![image](https://user-images.githubusercontent.com/1790201/70268684-ce5bc080-1755-11ea-82b6-4d991a0f6396.png)

**Comment by Tyriar** [comment]
We wouldn't want to statically link as then winpty would need to get loaded when loading pty.node, it's legacy so we wouldn't want that. I suggest looking into how we solve that in VS Code where winpty.dll is included in an unpacked folder:

![image](https://user-images.githubusercontent.com/2193314/70270929-357b7400-175a-11ea-9bbe-94a7bc6a7025.png)

I didn't set it up but it's definitely possible to use asar with node-pty.

**Comment by Marcus10110** [comment]
Thanks @Tyriar!

I was able to figure this out from the electron packager documentation and use the following asar options:

```
    asar: {
      unpack: '**/node_modules/node-pty/build/Release/*'
    },
```
This causes a `app.asar.unpacked` directory to be created along side `app.asar`, and it contains the specified files. The application "just works" - I didn't need to modify any paths in the rest of the app for it to locate pty.node in the new directory.

Thanks again!

**Comment by Tyriar** [comment]
Nice, good to hear 👍
