### ISSUE TITLE
process.on('SIGINT', fn) is no longer called after calling pty.spawn()

### ISSUE THREAD

**Issue by sdegutis** [microsoft/node-pty#373]
## Environment details

- OS: `10.15.1 (19B88)`
- node-pty version: `0.9.0`

## Issue description

I have `process.on('SIGINT', cleanupStuff)` and this works until the very first time that I call `pty.spawn(cmd, args, {env})`, after which it never gets called. I'm testing it by pressing ^C in the terminal in my Node.js process.

**Comment by Tyriar** [comment]
Same problem as https://github.com/microsoft/node-pty/issues/190?

**Comment by sdegutis** [comment]
I think so but not 💯% sure.

**Comment by Tyriar** [comment]
Looks like it, there's even a PR that's showing that this is the problem line:

https://github.com/microsoft/node-pty/blob/f3099ad49177197203b27e9450aef7c03530c375/src/unix/pty.cc#L147

**Comment by sdegutis** [comment]
Good find 👍 yeah that's the same issue.
