### ISSUE TITLE
About "module not found: error: can't resolve"

### ISSUE THREAD

**Issue by kangert666** [microsoft/node-pty#380]
## Environment details

- OS:linux
- OS version:4.19
- node-pty version:0.9.0

## Issue description
 warning  in ./node_modules/node-pty/lib/unixTerminal.js

Module not found: Error: Can't resolve '../build/Debug/pty.node' in '/media/kangert/Data/DevelopmentCode/Web/hktools/node_modules/node-pty/lib'

When I used node loader to solve a problem, I came up with a new problem. I don't know what to do now

**Comment by Tyriar** [comment]
Are you using some special loader/bundler to get this error?

**Comment by kangert666** [comment]
> Are you using some special loader/bundler to get this error?

Yes, if no node loader is used, other errors will be reported. When I use this, the program will run normally, but the node Pty terminal interface is not normal

**Comment by kangert666** [comment]
> Are you using some special loader/bundler to get this error?

Yes, other errors will be reported if node loader is not used, for example:


 ERROR  Failed to compile with 1 errors                                                                 9:46:54

 error  in ./node_modules/node-pty/build/Release/pty.node

Module parse failed: Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process thi
s file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)

 @ ./node_modules/node-pty/lib/index.js 49:49-85
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/SSH/SSHIndex.vue?vue&type=script&lang=js&
 @ ./src/components/SSH/SSHIndex.vue?vue&type=script&lang=js&
 @ ./src/components/SSH/SSHIndex.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.1.5:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

**Comment by kangert666** [comment]
When I use node loader, the program can run, but there is a problem in the node Pty terminal interface. The following is the error message:

![image](https://user-images.githubusercontent.com/47551853/74794079-33f32e00-52fd-11ea-943a-40083d57194a.png)

**Comment by Tyriar** [comment]
This is a webpack problem with locating the `.node` file, there are ways to fix it which I believe have already been discussed in issues. Searching issues for "webpack" should give you some insight
