### ISSUE TITLE
What is the proper way to kill the pty process in Electron?

### ISSUE THREAD

**Issue by MJomaa** [microsoft/node-pty#382]
## Environment details

- OS: Windows
- OS version: 10
- node-pty version: 0.9.0

## Issue description

I'm using Electron and spawn a new pty process in conjunction with xterm.js.
Is it enough to kill the spawned process on the window unload event when the app exits?

```
window.addEventListener('unload', (event) => {
  try {
    ptyProcess.kill();
  } catch (err) {
    try {
      ptyProcess.kill('SIGKILL');
    } catch (e) {
      // couldn't kill the process
    }
  }
});
```

**Comment by jerch** [comment]
Well - yes and no.

Yes: For well behaving cmdline progs under POSIX (linux, OSX, WSL) sending `SIGHUP` should bubble to all programs started under that terminal. Note that some shells only inform foreground programs, thus background processes might continue to run (like under bash). Furthermore processes can deliberately ignore `SIGHUP`(like with `nohup`, which swallows the signal).

No: For native windows processes (not WSL) it is more tricky, the processes have only a loose parent/child relation, there is nothing like "signal bubbling". Subprocesses are likely not to terminate here, unless your first process has some means to inform the subprocesses. To stop all processes here, you gonna need a process walker to identify the subprocesses and kill them "by hand".
