### ISSUE TITLE
node commands give env: node: no such file or directory

### ISSUE THREAD

**Issue by martijnmichel** [microsoft/node-pty#383]
## Environment details

- OS: MacOS
- OS version: Catalina
- node-pty version: latest

## Issue description
So I've made a little starter electron app where I included node-pty through xterm. When I try to run any node app like npm, quasar or firebase I get an error: 
env: node: no such file or directory.

When running this in the mac terminal obviously everything works fine else I wouldnt be able to start the electron app.

I've used the node-pty example mostly including the cwd and env config parameters set to process.env.HOME and process.env. Console logging process.env shows everything is present.

**Comment by Tyriar** [comment]
That's to do with either how you set the environment or how you launched the shell. The likely problem is you need to use `["-l']` as the args so that the shell is launched as a login shell which is the default for macOS.

**Comment by martijnmichel** [comment]
Great, it works! Thanks.
