### ISSUE TITLE
How do I stop a program with a button that does something like Ctrl+c?

### ISSUE THREAD

**Issue by penggelies07** [microsoft/node-pty#386]
## Environment details

- OS:macOs Mojave
- OS version:10.14.4 
- node-pty version:0.9.0

## Issue description
10.14.4 
How do I stop a program with a button that does something like Ctrl+c?

I want to stop the program by clicking the button, like CTRL +c. How do I do that?

**Comment by Tyriar** [comment]
You press ctrl+c? Note that node-pty doesn't work in isolation, you need to use it with a terminal emulator such as xterm.js.
