### ISSUE TITLE
The progress reveals the disorderly things

### ISSUE THREAD

**Issue by BinChenLiao** [microsoft/node-pty#389]
## Environment details
nodeApi.fs.writeFileSync(executeFile, this.runCodes)
    this.ls = nodeApi.pty('python.exe', ['test.py'], {
      name: 'xterm-color',
      cols: 380,
      rows: 330
    })

- OS: win10
- OS version:  1909
- node-pty version: 0.9

## Issue description
Call Python in this way, but expose some useless things

![image](https://user-images.githubusercontent.com/37283139/75852477-0b078880-5e27-11ea-9595-8a258f1c00ab.png)
![image](https://user-images.githubusercontent.com/37283139/75852494-122e9680-5e27-11ea-8a07-852c2bb90c95.png)

**Comment by BinChenLiao** [comment]
Call Python to output Hello World
But show     [2J[?25l[m[Hhello world
]0;C:\Users\admin\AppData\Local\Programs\codesprite-test\resources\app\dist\electron\static\Python3\python.exe[?25h

In electron
node versition  is 32bit

**Comment by jerch** [comment]
@BinChenLiao Sorry, its abit hard to grasp what your issue is. Maybe try to rephrase it? What is useless in the output?

**Comment by Tyriar** [comment]
@BinChenLiao I get the impression you're after the node child_process/exec apis.
