### ISSUE TITLE
Build Failure on Mac against NW.JS headers

### ISSUE THREAD

**Issue by akarsh42** [microsoft/node-pty#390]
## Environment details

- OS:MacOS
- OS version:10.15.3
- node-pty version:0.9.0
for NW.JS

## Issue description
not able to build the node-pty for NW.JS(node Webkit)

## error

> 

> prebuild info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
>   CXX(target) Release/obj.target/pty/src/unix/pty.o
> ../src/unix/pty.cc:644:10: error: use of undeclared identifier 'openpty'
>   return openpty(amaster, aslave, name, (termios *)termp, (winsize *)winp);
>          ^
> ../src/unix/pty.cc:693:10: error: use of undeclared identifier 'forkpty'
>   return forkpty(amaster, name, (termios *)termp, (winsize *)winp);
>          ^
> 2 errors generated.
> make: *** [Release/obj.target/pty/src/unix/pty.o] Error 1
> prebuild ERR! build error 
> prebuild ERR! stack Error: `make` failed with exit code: 2
> prebuild ERR! stack     at ChildProcess.onExit (/Users/kh1095/.nvm/versions/node/v11.14.0/lib/node_modules/prebuild/node_modules/nw-gyp/lib/build.js:271:23)
> prebuild ERR! stack     at ChildProcess.emit (events.js:193:13)
> prebuild ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:255:12)
> prebuild ERR! not ok 
> prebuild ERR! build Error: `make` failed with exit code: 2
> prebuild ERR! build     at ChildProcess.onExit (/Users/kh1095/.nvm/versions/node/v11.14.0/lib/node_modules/prebuild/node_modules/nw-gyp/lib/build.js:271:23)
> prebuild ERR! build     at ChildProcess.emit (events.js:193:13)
> prebuild ERR! build     at Process.ChildProcess._handle.onexit (internal/child_process.js:255:12)

## missing definitions in util.h 

 build picks up the wrong utils.h and therefore can't find openpty/forkpty, 

the header files for NW.JS has util.h which doesn't have declaration for the function  openpty and forkpty is being pucked up

 prebuild against Node headers goes through fine.

**Comment by Tyriar** [comment]
This is likely because NW.js is on an old version of node which is why the headers can't be picked up, we only target relatively recent versions of node if that's the case.
