### ISSUE TITLE
Error spawning a terminal when one of the options passed is not a string

### ISSUE THREAD

**Issue by chaitanyathengdi** [microsoft/node-pty#395]
## Environment details

- OS: Windows 10 Professional x64
- OS version: 10.0.18363
- node-pty version: 0.9.0

## Issue description
I'm trying to create a terminal to `ssh` into WSL.

```JS
// init
sshuser = '' || 'chaitanya'
sshhost = 'localhost'
sshport = 22
sshauth = 'password'

// spawn
pty.spawn('ssh.exe', [sshuser ? (sshuser + '@' + sshhost) : sshhost, '-p', sshport, '-o', 'PreferredAuthentications=' + sshauth], {
  name: 'xterm-256color',
  cols: 80,
  rows: 30
}); // Error: TypeError: arg.indexOf is not a function
```
The error disappears if instead of passing just `sshport`, we pass `sshport.toString()`.

BTW I checked the code, and nothing is showing up for `arg.indexOf`. Most that I can find is this:
`var commandLine = argsToCommandLine(file, args);`
(windowsPtyAgent.js, line 70)
Don't know what happens to `args` after this.

**Comment by Tyriar** [comment]
Sure we can add a guard here, I'll probably just throw though to make it obvious what's wrong.

https://github.com/microsoft/node-pty/blob/48bacd0260c9460cb0de6043b72aef0fe0f8b93f/src/windowsPtyAgent.ts#L267-L268
