### ISSUE TITLE
How to ship node-pty build with electron app?

### ISSUE THREAD

**Issue by martijnmichel** [microsoft/node-pty#400]
## Environment details

- OS: Manjaro Linux
- OS version: Latest
- node-pty version: 0.9.0

## Issue description
https://images-ext-1.discordapp.net/external/hUW7s4uRBD6GbRRt94QW59zAZ6G56agzx2Yq4dOk-v8/https/i.imgur.com/gtLCdwq.png?width=578&height=468

Somehow the reference path to node-pty is using my local directory structure when I require('node-pty'). Ofcourse this doesnt give me any problems when I use the app on my own machine, but I can't seem to include the correct path in build so others can use it.

**Comment by Tyriar** [comment]
This is probably a native node module packaging issue? I suggest looking at how node-pty embedders do it (like Hyper, VS Code, etc.) to find out how to properly do this.

**Comment by martijnmichel** [comment]
If theres any chance you can point me in the right direction I would be very grateful. Im having a hard time figuring this out and Hyper/VSCode repos are very large.

**Comment by Tyriar** [comment]
@martijnmichel this question would be better asked to someone more familiar with however you're packaging your app.
