### ISSUE TITLE
Docker builds Debug not Release?

### ISSUE THREAD

**Issue by theflyingape** [microsoft/node-pty#404]
## Environment details

- OS: Linux
- OS version: 5.5.17-200.fc31.x86_64
- node-pty version: 0.9.0

## Issue description

Running this from bash works perfectly and the node-pty install makes:
```
$ ll node_modules/node-pty/build/Release/
total 44
-rwxrwxr-x 1 rhurst rhurst 43424 Apr 21 08:56 pty.node
```
For whatever reason, the `npm install` portion of a docker image build is making a pty.node in a "Debug" folder, and not in Release.  It throws this:
```
$ docker-compose up
...
> node-pty@0.9.0 install /usr/src/dankdomain/node_modules/node-pty
> node scripts/install.js

make: Entering directory '/usr/src/dankdomain/node_modules/node-pty/build'
  CXX(target) Debug/obj.target/pty/src/unix/pty.o
  SOLINK_MODULE(target) Debug/obj.target/pty.node
  COPY Debug/pty.node
make: Leaving directory '/usr/src/dankdomain/node_modules/node-pty/build'

> utf-8-validate@5.0.2 install /usr/src/dankdomain/node_modules/utf-8-validate
> node-gyp-build


> node-pty@0.9.0 postinstall /usr/src/dankdomain/node_modules/node-pty
> node scripts/post-install.js
...
app_1  | innerError Error: Cannot find module '../build/Debug/pty.node'
app_1  | Require stack:
app_1  | - /usr/src/dankdomain/node_modules/node-pty/lib/unixTerminal.js
```
I've tried it with this in Dockerfile with no joy:
```
ENV NODE_ENV production
ENV NODE_PTY_DEBUG 0
```
What's the missing ingredient here please?

**Comment by jerch** [comment]
Was the node binary build in debug mode by any chance? This might be relevant here: https://github.com/nodejs/node-gyp/issues/743.

Also can you check whether appending an else-clause containing `gypArgs.push('--release');` will help here: https://github.com/microsoft/node-pty/blob/cd72d3303cb484e402381741e7e6a613886eda7b/scripts/install.js#L8-L10

**Comment by Tyriar** [comment]
Don't see why docker would impact this, plus we don't include a dockerfile in the repo?

**Comment by theflyingape** [comment]
Ok, I removed node-pty from the node_module, and tried again with ENV NODE_PTY_DEBUG 0
```
> node-pty@0.9.0 install /usr/src/dankdomain/node_modules/node-pty
> node scripts/install.js

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: socket hang up
gyp ERR! stack     at connResetException (internal/errors.js:608:14)
gyp ERR! stack     at TLSSocket.socketOnEnd (_http_client.js:460:23)
gyp ERR! stack     at TLSSocket.emit (events.js:322:22)
gyp ERR! stack     at endReadableNT (_stream_readable.js:1187:12)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:84:21)
gyp ERR! System Linux 5.5.17-200.fc31.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--debug"
gyp ERR! cwd /usr/src/dankdomain/node_modules/node-pty
gyp ERR! node -v v12.16.2
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
```
Now I think I am chasing a red herring.  It seems this is dependent on glibc and I am only using a node docker image:
```
web_1  | Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /usr/src/dankdomain/node_modules/node-pty/build/Release/pty.node)
```
Is there a sample working Dockerfile?  Thanks for the excellent module and for checking into this!

**Comment by Tyriar** [comment]
No, but I'd expect it to work fine in a regular Debian docker image as I've never had problems compiling it on Linux. You've already found the code that sets debug mode so I'm not sure what's going on. Perhaps npm verbose logging will tell you what's getting run?

**Comment by theflyingape** [comment]
Thanks, I ended up changing out (any) node image and went with centos to include its **glibc** which was definitely the missing ingredient, i.e.,
```
FROM centos:8
EXPOSE 1939

ENV LANG=C.UTF-8
RUN dnf -y upgrade-minimal
RUN dnf -y module install nodejs:12/development
RUN dnf -y install openssl python36 gcc-c++ make
```

**Comment by jerch** [comment]
@theflyingape Btw - we just changed to node v14 as development base, you might want to change that as well. Otherwise it will break again as soon as we use the first v14 symbol :smile_cat:
