### ISSUE TITLE
The same content is repeated multiple times in the output stream

### ISSUE THREAD

**Issue by FeodorFitsner** [microsoft/node-pty#408]
## Environment details

- OS: Windows 10
- OS version: 1909
- node-pty version: 0.9.0

## Issue description

I'm trying to generate a "colored" output from a script by running it with `node-pty`.

Consider the following example:

```js
var pty = require('node-pty');

var ptyProcess = pty.spawn('powershell.exe', ['-command', 'git --version;echo "Message 1";pwsh --version;echo "Message 2";'], {
  name: 'xterm-color',
  cols: 80,
  rows: 30,
  cwd: process.env.HOME,
  env: process.env
});

ptyProcess.on('data', function(data) {
  process.stdout.write(data);
});
```

When running the sample program in Windows console it produces expected results:

![image](https://user-images.githubusercontent.com/5041459/81597440-94cd5800-937a-11ea-9069-65160ea4d403.png)

However, when reading the sample's StdOut stream from another program (or redirecting the output to some file `node sample.js > log.txt`) it repeats the same content multiple times: https://gist.githubusercontent.com/FeodorFitsner/033167b924b98d29e077c86ee5945c47/raw/03c0294400c5acc9098be6014ee03a08bfdf6e18/output.txt

Yes, the output contains control sequences moving cursor and overwriting content, but that doesn't work if you collect an output to the log - there are sections of repeated content.

I see Windows 10 1809+ uses ConPty API under the hood, while older Windows versions fall back to WinPty with agents. WinPty does not expose such behavior.

Is there any way to get ConPty work the same way as WinPty?

**Comment by jerch** [comment]
> However, when reading the sample's StdOut stream from another program (or redirecting the output to some file node sample.js > log.txt) it repeats the same content multiple times:

For most interactive cmdline programs this is not a good idea as it is likely to contain terminal sequences. Still many POSIX coreutils can be piped w'o sequences since they determine at runtime with `isatty` if they are writing to a buffered pipe or a TTY. Windows does not have the needed termios semantics to do this slightly different handling based on stdout file descriptor type.

> Yes, the output contains control sequences moving cursor and overwriting content, but that doesn't work if you collect an output to the log - there are sections of repeated content.

To get the output terminal sequences - route the data through a terminal sequence parser with rudimentary terminal abstraction and catch all printables.

> Is there any way to get ConPty work the same way as WinPty?

Imho you can still switch `node-pty` to use winpty, if you really want that. Note that winpty has many issues itself, also not sure if it is still actively maintained.

**Comment by FeodorFitsner** [comment]
Thanks for looking into that!

Actually, it's the whole point of the exercise - getting terminal ANSI sequences in the output, by making programs in a build script believe they are running on a TTY.

We are currently working on colour support in Windows builds on AppVeyor CI. Emulating TTY on Linux/macOS has been working great for ages with `openpty/forkpty` ([sample build](https://ci.appveyor.com/project/appveyor-tests/bash-builtin-linux/builds/32754203)). Windows, however, was lacking PTY until WinPty. WinPty works good-ish too, but not as smooth as Linux stuff, because it's polling console buffer of a shadow process (winpty agent). There are quirks sometimes, but [it works](https://ci.appveyor.com/project/appveyor-tests/service-fabric-docker#L24).

We've been hoping to replace WinPty with built-in ConPty available in latest Windows builds, if that's possible, so I was wondering if there is a "mode" in ConPty to make it work similar to WinPty, without re-drawing/repeating content? Let me know if I need elaborate more.

**Comment by jerch** [comment]
> We've been hoping to replace WinPty with built-in ConPty available in latest Windows builds, if that's possible, so I was wondering if there is a "mode" in ConPty to make it work similar to WinPty, without re-drawing/repeating content? Let me know if I need elaborate more.

There was some discussion about a passthrough mode for ConPty, not sure if it ever left the testbed state. See https://github.com/microsoft/terminal/issues/1173 for a discussion about that approach and input from some terminal emulator devs. Also `node-pty` cannot do much about it, as it is basically a proxy for ConPty API into nodejs realms. Maybe ask over there?

In the meantime I see only two options for you - either stick with winpty for now, or hook up some sequence parser with limited terminal abstraction, that can deal with the "fullscreen repaints". From there you could do some buffer diff scraping with colors preserved. Thats basically what winpty does in the first place, but ConPty will give you UTF-8 and a wider color range support. Ofc, both is less than ideal...

**Comment by FeodorFitsner** [comment]
@jerch thanks for the links! I went through the discussions and understood that WinPty perhaps is the only option for now. Maybe in the future we'll try implementing something like a buffer, but it sounds complicated. Thank you for your time digging that!
