### ISSUE TITLE
README.md Dependencies section does not mention Mac instructions

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [microsoft/node-pty#411]
https://github.com/microsoft/node-pty/blob/bcdc826f365dd014403992d41b286e815798459a/README.md#dependencies

There are installation instructions for:
* Linux/Ubuntu: `apt-get`, which is not natively available on MacOS
* Windows: `windows-build-tools`

Could the documentation be updated to also include recommended instructions for Mac please?

**Comment by Tyriar** [comment]
I don't think there are dependencies on mac, maybe xcode? Have you had problems installing it there?

**Comment by JoshuaKGoldberg** [comment]
No problems here, but I have previously run `xcode-select --install` and some other potential dependencies for unrelated reasons. If there are no dependencies or that's the only one, it would be nice to list that in the README.md.
