### ISSUE TITLE
Spawning an interactive REPL child process via node-pty 

### ISSUE THREAD

**Issue by repthesaj** [microsoft/node-pty#418]
I'm trying to build a browser-based REPL for Python like in REPL.it (http://repl.it/). When the user clicks "Run Code," I'm using **node-pty** to spawn a child process which creates an interactive Python REPL instance within a Docker container, like so:

<img width="1030" alt="Screen Shot 2020-07-13 at 10 40 24 AM" src="https://user-images.githubusercontent.com/68265468/87387246-29a92900-c557-11ea-8c82-f092a79ff683.png">

How can I tell when a program finishes executing without waiting for the spawned child process to exit (i.e. process.on('exit', {...}) since after the program is executed, users can still interact with methods declared in the program (in order for the shell GUI to be interactive this means the process never exits)?

**Comment by jerch** [comment]
@repthesaj 
That question is not directly related to `node-pty`, as it only provides IO with TTY semantics.

Still trying to answer your question:
You need to be clear about what a "program" in your REPL is, more precisely what the execution unit looks like and how and to what extend it is isolated from the REPL context. So this is solely a problem of the REPL itself, examples:
- In a shell the execution unit is typically a system process with high isolation, only loosely coupled to the parent process (shell REPL itself), processes always run concurrent and bring their own semantics to ask or alter their state (wait, kill etc)
- In a python REPL your execution unit might be a function in the same interpreter context with low to none isolation, no concurrency etc. or a more complex REPL setup with threading/generators/coroutines or even subprocesses.

Now back to your question:

> How can I tell when a program finishes executing without waiting for the spawned child process to exit

This already mixes things up, or maybe it is just a wording issue (not sure, where the process notion comes from). Your question sounds like you want to able to tell, whether your program still runs. Well for very simple REPLs, that execute "programs" within the same thread context, it is this simple - until the execution hasn't returned to your REPL code, it still runs. Imho the default python REPL acts this way. (Here the TTY semantics of `node-pty` might come handy, as it provides catchable interrupts.)
To tell whether the program still runs, while it is running, you need concurrency. This can be achieved with a second interpreter process, to which you redirect I/O. Imho the oldish tkinter IDE (was it called IDLE?) acted this way. Or on a smaller scale with less isolation - with threading. Here your REPL can simply inspect the state of the thread. Or if your REPL has a strong emphasis on **E**val - you could also build your own AST and feed single instructions to some interpreter context. This could be done by a generator, which still executes while it is not exhausted.

Summary:
It depends alot on your REPL internals.

**Comment by repthesaj** [comment]
Thanks for the insights @jerch ! By "program," I was referring to the Python file, **main.py**, which contains code to be executed. When the user clicks "Run," I use node-pty to spawn an isolated child process `python3 -i main.py` in a Docker container which first **(1)** executes a copy of **main.py** and then **(2)** enters interactive Python shell mode––all within the same child process (never exits at all).

Thus I suppose what I'm trying to ask is how would I determine at what point in time does the script `python3 -i main.py` finish **(1)** executing **main.py** before **(2)** entering interactive Python shell mode. In other words, is there some way for node-pty to determine if **main.py** is still being executed?

**Comment by jerch** [comment]
You basically want to inform the process running `node-pty` from another process (your python script), that something happened. Well for that you can use typical IPC mechanisms, from sockets, fifos, to shared memory or custom OS signals. Or use the pty channel itself (which already is an established fifo in the IPC sense).

Simple method to use the pty channel:
- print on python some sentinel to stdout when done with your main function, that would not occur otherwise from normal output
- in the `node-pty` process search for that sentinel
- if it was found, main execution has ended

**Comment by repthesaj** [comment]
Makes sense, thank you @jerch !
