### ISSUE TITLE
Character overlapped at the end of column

### ISSUE THREAD

**Issue by lee95292** [microsoft/node-pty#419]
## Environment details

- OS: Linux 
- OS version: Ubuntu 18.04.2 LTS
- node-pty version: 0.9.0

## Issue description

source code

```javascript
var os = require('os');
var pty = require('node-pty');
var shell = 'bash';

var ptyProcess = pty.spawn(shell, [], {
	name: 'xterm-256color',
	cols: 10,
	rows: 26,
	cwd: process.env.HOME,
	env: Object.assign({ TEST: "Environment vars work" }, process.env),
	useConpty: true
});

ptyProcess.onData(data => {
	process.stdout.write(data);
	console.dir(data,{depth:3});
});

var command = 'find -type f -execdir file -i {} \\;|grep charset=utf \r';

setTimeout(() => ptyProcess.write(command), 100);

process.on('exit', () => ptyProcess.kill());

setTimeout(() => process.exit(), 10000);
```

output 
`
'find -t\rtype f -exe\recdir file \r -i {} \\;|g\rgrep charse\ret=utf \r\n'
`

---

'find -t\r**t**ype f -exe\r**e**cdir file \r -i {} \\;|g\r**g**rep charse\r**e**t=utf \r\n'

After CR, former character(in this line : t,e,g,e) was duplicated.

why does it happen?

**Comment by Tyriar** [comment]
This is what I see running it off master (`0.10.0-beta13`):

![image](https://user-images.githubusercontent.com/2193314/87674500-ef908080-c72a-11ea-8648-74d6029044f4.png)

**Comment by lee95292** [comment]
Version 0.10.0-beta13 same to me.
i tested 0.9.0(latest), 0.10.0-beta13, at Linux(ubuntu 18.04), OSX (Catalina 10.15.4)
as different as your image, my result has '\r' at every end of cols value.

![image](https://user-images.githubusercontent.com/30853787/87774343-5f078c80-c85f-11ea-98ac-59cfe4d4dea6.png)

In node-pty@0.9.0, somtimes character duplicated at the every end of cols. 

Tell me about info whatever  you wants.

Thanks.

**Comment by jerch** [comment]
@lee95292 

The duplicates are most likely created by the interactive shell running the TTY in raw mode. Try using `dash` instead, which relies on ICANON (cooked mode) in the TTY instead.

**Comment by lee95292** [comment]
@jerch  thanks! 

(To someone with the same problem)
https://en.wikipedia.org/wiki/Terminal_mode
https://unix.stackexchange.com/questions/21752/what-s-the-difference-between-a-raw-and-a-cooked-device-driver

**Comment by MyunghoBae** [comment]
How did you fix this problem?
