### ISSUE TITLE
Instructions for using node-pty with Electron?

### ISSUE THREAD

**Issue by pickhardt** [microsoft/node-pty#422]
## Environment details

- OS: Mac
- OS version: 10.14.6
- node-pty version: 0.9.0

## Issue description

Are there instructions for using this project with Electron? I am using Electron 9.1.2 and ran the npm_install.sh command (from https://github.com/microsoft/node-pty/blob/master/examples/electron/npm_install.sh) but with 9.1.2 instead of 9.1.0

However I am still seeing the following when starting Electron:

```
./node_modules/node-pty/lib/windowsPtyAgent.js
Module not found: Can't resolve '../build/Debug/conpty.node' in '/Users/jeffmac/projects/electro/application/node_modules/node-pty/lib'

./node_modules/node-pty/lib/unixTerminal.js
Module not found: Can't resolve '../build/Debug/pty.node' in '/Users/jeffmac/projects/electro/application/node_modules/node-pty/lib'

./node_modules/node-pty/lib/windowsPtyAgent.js
Module not found: Can't resolve '../build/Debug/pty.node' in '/Users/jeffmac/projects/electro/application/node_modules/node-pty/lib'

./node_modules/node-pty/lib/windowsPtyAgent.js
Module not found: Can't resolve '../build/Release/conpty.node' in '/Users/jeffmac/projects/electro/application/node_modules/node-pty/lib'
```

I'm unsure what the build and install process is for node-pty with Electron.

**Comment by Tyriar** [comment]
The same you're pointing out is the example on how to use it in Electron, I don't know about 9.1.2 but 9.1.0 support was added very recently: https://github.com/microsoft/node-pty/commit/400146f9b299a9c9684c9ba221376007248f2c75

Try cloning node-pty's repo and running the example.

**Comment by imagineeeinc** [comment]
This worked for me, and for future users who want to use node-pty with electron:

I had a project which needed Robot JS in electron so I needed to rebuild it for the electron runtime.

I found [this](https://github.com/octalmage/robotjs/issues/594#issuecomment-673859334) which helped for Robot JS.

So, I used it on node-pty and it worked the command (I am using windows):
```cmd
cd .\\node_modules\\node-pty && node-gyp rebuild --target=10.1.5 --arch=x64 --target_platform=darwin --dist-url=https://atom.io/download/atom-shell
```

- --target is the electron version
- --arch is the architecture

Hope this helps and for others who finds this

**Comment by whitehacker** [comment]
I have got a similar issue: 

- Node: v18.17.1
- ElectronJS: 27.0.3
- macOS Sonoma M2

1. `innerError Error: Cannot find module '../build/Debug/pty.node'`

2. `Uncaught Error: Loading non-context-aware native module in renderer: `

**Comment by babaheer** [comment]
> I'm also facing the same issue. @whitehacker did you solve this problem?

Sadly, no, the issue still persists.
