### ISSUE TITLE
Sending command directly to process without input into terminal window

### ISSUE THREAD

**Issue by ThomasSydney** [microsoft/node-pty#429]
## Issue description

I'm just beginning to look into terminal emulation as well as node-pty and xterm.js so apologies if I'm missing something, but I wondered if it was possible to send a command directly to bash without displaying/typing the input into the terminal. For example sending "ls -ltr" in code, without typing it into the terminal and capturing the output to be used for other purposes. 

I've tried a few things such as writing directly to the pty process i.e. ptyProcess.write("ls -ltr") but this still displays the input in the terminal window.

I've read around the area with respect to tty's and tried to dig around in the code around the sockets but didn't get too far.

## Current setup code
```
 const ptyProcess = pty.spawn('zsh', [], {
    name: 'xterm-256color',
    cwd: process.cwd(),
    env: process.env,
  });

  // Initialize xterm.js and attach it to the DOM
  const xterm = new Terminal();
  xterm.open(document.getElementById('xterm'));

  // Setup communication between xterm.js and node-pty
  xterm.onData((data) => ptyProcess.write(data));
  ptyProcess.on('data', function (data) {
    xterm.write(data);
  });
```

A few things I've tried:

```
    xterm._core._coreService._onData.fire('echo foo\r');

    const echoTest = `echo Hello > ${ptyProcess._pty}`;
    spawnSync(echoTest);

    ptyProcess.write("ls -ltr");
```

Any help would be greatly appreciated!

**Comment by Tyriar** [comment]
This is the way to do this:

```
ptyProcess.write("ls -ltr")
```

But your shell is echoing out what you typed, so you would need to either configure your shell not to do that (I don't know if you can) or suppress the output on the terminal side (which is probably a bad idea).

Alternatively you can execute a script or something in node-pty `bash ["-c", "<script>"]` to avoid echoing.

**Comment by ThomasSydney** [comment]
> This is the way to do this:
> 
> ```
> ptyProcess.write("ls -ltr")
> ```
> 
> But your shell is echoing out what you typed, so you would need to either configure your shell not to do that (I don't know if you can) or suppress the output on the terminal side (which is probably a bad idea).
> 
> Alternatively you can execute a script or something in node-pty `bash ["-c", "<script>"]` to avoid echoing.

Thanks for replying so quickly, I'll give those suggestions a go!

**Comment by ThomasSydney** [comment]
@Tyriar Would you be able to clarify a little more on your suggestions please :)
This doesn't run the command it just puts it into the terminal:
`ptyProcess.write("ls -ltr")`

I can simulate an input by adding an "\r" but then I'm still unsure how to prevent the input displaying? Do you have any further suggestions?

Also how could I go about executing a bash script inside a bash process, again without showing the input to the terminal?

Thanks again 👍

**Comment by Tyriar** [comment]
The `\r` would run it yet, it sounds like the last suggestion is what you're after; creating a new shell to run the command, then that would only show the output of that command, not the prompt.

> Alternatively you can execute a script or something in node-pty bash ["-c", "<script>"] to avoid echoing.

**Comment by jerch** [comment]
@ThomasSydney The official way to do that is by telling a program on the other side not to mirror input back (echoing), as @Tyriar wrote. Either that program has a switch to silent the input or you cannot do it reliably.

For POSIX likes there is another way by directly telling the TTY to switch off ECHO (see termios settings). Whether this works for your shell (or other programs to be used) you can test by running the following in a terminal:

```
$> stty -echo
$> # here input should be silent but still work normally
```

But note that this is unreliable, as a program is free to reset this at any time (this can be circumvented by tracking the setting and switching it off again). Last but not least there are programs acting on a TTY in raw mode. In that mode the program might do the echoing on its own not being affected by ECHO at all.

In case you wonder why this cannot be orchestrated in a straight forward manner from a PTY master end (thats what node-pty is about) - the whole TTY/PTY logic is meant for dumb terminals, where the program on the other end has the controlling power for most output settings and the terminal end is just an output "dumpster". It is hardcoded that way in the kernel as part of the POSIX termios interface. The term "dumb terminal" goes back to the 70s and describes a class of terminals, that would have no additional logic beside creating characters (input) and displaying characters with cursor movement (output). Here input has to be sent into the TTY kernel interface first, before getting mirrored back. The terminal itself is not expected to have its own idea/logic for different handling. Yes, terminals are still sitting on 50 years old interfaces ;)
