### ISSUE TITLE
Module parse failed: Unexpected character '' (1:0) with electron and webpack

### ISSUE THREAD

**Issue by cefuroX** [microsoft/node-pty#435]
## Environment details

- OS: Fedora
- OS version: 32
- node-pty version: 0.10.0-beta18
- node version: v12.19.0

## Issue description

Hi all.
I try to load node-pty in a fresh electron application. Since there is a webpack behind the build i get the following error:

```
in ./node_modules/node-pty/build/Release/pty.node

Module parse failed: Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
```

I think its more webpack than node-pty but I can't find any help online, maybe someone of you can tell me whats going wrong here? 
I searched already for the issue but no solution worked for me :) 

Thanks for your help

**Comment by mofux** [comment]
This is a native module (with C bindings) that has to be compiled (it compiles into the `pty.node` binary). It is not supposed to get bundled by webpack. You should either exclude it from bundling, or if for some reason you really want to bundle it, you could try to use https://webpack.js.org/loaders/node-loader

**Comment by cefuroX** [comment]
I already thought that I should exclude it but I can't find a documentation for it to exclude it in my config :thinking: Maybe I'm blind or something. I need this to handle shell stuff in my electron backend so no reason to bundle it in my Frontend :)

**Comment by cefuroX** [comment]
:thinking:  Even if I try to exclude the background.js he tries to parse the background.js. I have no clue how to exclude the files. 

```javascript
const path = require('path');

module.exports = {
    configureWebpack: {
        devtool: 'source-map',
    },
    chainWebpack: config => {
        config.module
            .rule('ignore-node')
            .test(/\.node$/)
            .exclude
                .add(path.resolve(__dirname, 'node_modules/node-pty/build/Release/pty.node'))
                .add(path.resolve(__dirname, 'src/background.js'));
  
        config.module.rule('js')
            .exclude
                .add(path.resolve(__dirname, 'node_modules/node-pty/build/Release/pty.node'))
                .add(path.resolve(__dirname, 'src/background.js'));
    }
}
```

**Comment by saumyasinghal747** [comment]
I am using Vue CLI and electron-builder. I solved my problem by adding the following to my `vue.config.js`:
```js
module.exports = {
    "pluginOptions":  {
        "electronBuilder": {
          "nodeIntegration": true,
           externals:['node-pty']
        }
    }
}
```

After that, I removed my `node_modules` folder and ran `npm rebuild node-pty --update-binary` and then I ran `npm install`. Everything worked smoothly after that. Hope this helps!

**Comment by mofux** [comment]
#359 is a similar issue.

**Comment by cefuroX** [comment]
@saumyasinghal747 thnx this worked for me. Didn't had to rebuild node-pty but could be a good addition for others.
@mofux thnx for your help too.

**Comment by michielkempen** [comment]
Hey @lyssar 

I've spent my whole afternoon fighting this very problem, without any luck. 😞

I've tried every possible solution that I could find online and my entire Google search looks purple. I literally don't have a clue what I could try next, so if you would be willing to share a little more details about your solution, that would be very helpful.

My development setup is the following:
- OS: macOS
- OS version: 10.15.6
- node-pty version: 0.9.0
- node version: v15.1.0

My electron application is built using version 2.0.0-rc.4 of the [Vue-cli Electron Builder plugin](https://github.com/nklayman/vue-cli-plugin-electron-builder).

My `vue.config.js` file looks like this:

```js
var path = require('path');

module.exports = {
  pages: {
    index: {
      entry: 'src/app/main.js',
    },
  },
  chainWebpack: config => {
    config.resolve.alias.set('@', path.resolve(__dirname, 'src/'));
  },
  pluginOptions: {
    electronBuilder: {
      nodeIntegration: true,
      externals: ['node-pty']
    }
  },
};
```

In my `package.json` I have the following scripts:

```js
"scripts": {
  "build": "vue-cli-service electron:build",
  "serve": "vue-cli-service electron:serve",
  "postinstall": "electron-builder install-app-deps",
  "postuninstall": "electron-builder install-app-deps",
},
```

In my `background.js` file (the backend), I import the `node-pty` module at the top as follows:

```
import pty from 'node-pty';
```

But whenever I run `npm run serve`, I keep getting the following error:

```
 ERROR  Failed to compile with 1 errors                                                                                                                                                               8:57:31 PM

 error  in ./node_modules/node-pty/build/Release/pty.node

Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)

 @ ./node_modules/node-pty/lib/index.js 49:49-85
 @ ./src/background.js
 @ multi ./src/background.js
```

**Comment by saumyasinghal747** [comment]
Did you rebuild as mentioned?

**Comment by michielkempen** [comment]
Thank you for your reply @saumyasinghal747, really appreciate it!

Yes, I ran `npm rebuild node-pty --update-binary` and even tried rebuilding with [electron-rebuild](https://github.com/electron/electron-rebuild), but nothing seems to help...

For reference, I also created [an issue](https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/1156) in the vue-cli-plugin-electron-builder repository.

**Comment by michielkempen** [comment]
I finally found the solution to my problem: https://github.com/electron/electron-rebuild/issues/75#issuecomment-504637837

[electron-rebuild](https://github.com/electron/electron-rebuild/) does not rebuild the modules that are installed as devDependency. Once I installed the module as a dependency, electron-rebuild did its thing and everything worked as expected.
