### ISSUE TITLE
Building node-pty with webpack as a typescript import is failing

### ISSUE THREAD

**Issue by AlexChipev** [microsoft/node-pty#442]
## Environment details

- OS: Windows
- OS version: 10
- node-pty version: 0.9.0
- node version: 14.15.1

## Issue description
When import the node-pty module (import * as pty from "node-pty) in a typescript file and try to build it with webpack (using ts-loader) fails:

![image](https://user-images.githubusercontent.com/12774409/100528084-72e5d680-31e1-11eb-964f-67b085ba28f9.png)

**Comment by Tyriar** [comment]
I don't know how to configure it in webpack exactly, but you need to get it to recognize conpty.node/winpty.node are native node modules.

**Comment by growthepie** [comment]
Could you get this working @AlexChipev? I've tried everything to get it to work with an electron-ts-webpack setup with no success.
