### ISSUE TITLE
Terminal cannot enter commands

### ISSUE THREAD

**Issue by yyy19961027** [microsoft/node-pty#444]
## Environment details
Some computers run demo, enter commands, the commands are not displayed in the terminal, and the console reports an error indicating that the websocket connection is disconnected.
Browser and browser version: google
OS version: win10
xterm.js version: 4.9.0
node :=14.15.0

## Issue description
1.start the demo
2.enter commands
![terminal -error](https://user-images.githubusercontent.com/66300848/100562614-2a204180-32f7-11eb-87bc-4bb8ccbb3991.png)

**Comment by Tyriar** [comment]
https://github.com/xtermjs/xterm.js/issues/3183
