### ISSUE TITLE
Depend on the environment?

### ISSUE THREAD

**Issue by zhangbaojia** [microsoft/node-pty#445]
## Environment details

- OS: Window
- OS version: 10
- node-pty version: 0.9.0

## Issue description
I found that Node-Pty installed in the NodeJS15 environment ran error reporting on nodeJS12.
How to do nodeJS version can be switched at will after installation.

**Comment by Tyriar** [comment]
You need to reinstall the module when you change the node version:

```
rm -rf node_modules/node-pty
npm i
```
