### ISSUE TITLE
Environment variable truncated when packaged

### ISSUE THREAD

**Issue by wonkyungup** [microsoft/node-pty#455]
## Environment details

- OS: mac
- OS version: 11.1
- node-pty version: v12.18.2
## Issue description

Environment variables come out well in developer mode, but if I package them, environment variables don't come out. What should I do to read them as they are? (process.env)

**Comment by Tyriar** [comment]
What do you mean package?

**Comment by wonkyungup** [comment]
The same issue exists, so we've already solved it. Thank you.
