### ISSUE TITLE
Cls command bug

### ISSUE THREAD

**Issue by Womercode** [microsoft/node-pty#462]
## Environment details

- OS: Windows
- OS version: 10
- node-pty version: 0.9.0

## Issue description

Hey,

I'm creating an app with electron.js and I created a terminal. But when I execute the "cls" command, I must press enter to see
the "C:\Users\myuser\".

Here is my code : 

base.js
```
var pty = require('node-pty');
var Terminal = require('xterm').Terminal;

// Initialize node-pty with an appropriate shell
const shell = process.env[os.platform() === 'win32' ? 'COMSPEC' : 'SHELL'];
const ptyProcess = pty.spawn(shell, [], {
  name: 'xterm-color',
  cols: 80,
  rows: 30,
  cwd: process.cwd(),
  env: process.env
});

// Initialize xterm.js and attach it to the DOM
const xterm = new Terminal();
xterm.open(document.getElementById('xterm'));

// Setup communication between xterm.js and node-pty
xterm.onData(data => ptyProcess.write(data));
ptyProcess.on('data', function (data) {
  xterm.write(data);
});
```

I wrote `app.allowRendererProcessReuse = false;` in my main.js

Thanks in advance.

**Comment by Tyriar** [comment]
Not clear exactly what the problem is here, but anything to do with cls is related to [conpty](https://github.com/microsoft/terminal), you should test out the behavior in Windows Terminal.
