### ISSUE TITLE
Running multiple commands in same bash subsession

### ISSUE THREAD

**Issue by moltenice** [microsoft/node-pty#463]
## Environment details

- OS: Ubuntu
- OS version: 18.04.2 LTS
- node-pty version: 0.10.0

## Issue description

Imagine this contrived scenario:

./main.sh

```shell
source ./config.sh
SOME_CONFIG="${SOME_CONFIG}bar"
./output.sh
```

./config.sh

```shell
export SOME_CONFIG='foo'
```

./output.sh

```shell
echo "Config is: ${SOME_CONFIG}"
```

-------

I am trying to replace ./main.sh with a Node JS powered ./main.js WITHOUT replacing the other shell files.

I have tried a bunch of things but the below is the furthest I got.

./main.js

```javascript
var os = require('os');
var pty = require('node-pty');

var shell = os.platform() === 'win32' ? 'powershell.exe' : 'bash';

(async () => {
    try {
        var ptyProcess = await pty.spawn(shell, [], {
            name: 'xterm-color',
            cwd: process.cwd(),
            env: process.env,
        });

        ptyProcess.onData(function (data) {
            process.stdout.write(data);
        });

        await ptyProcess.write('source ./config.sh\r');
        process.env.SOME_CONFIG = `${process.env.SOME_CONFIG}bar`;
        await ptyProcess.write('./output.sh\r');
        await ptyProcess.write('exit\r');
    } catch (e) {
        console.error(e);
    }
})();
```

It doesn't work as expected:

1. I don't know how to just display the output to stdout. It outputs the bash commands themselves etc.
1. All the writes are going through in one go. I think this is expected behaviour for a pty like this but doesn't help me achieve what I am trying to achieve.
1. There is no way for me to check if a command ran or not. The `await`s I have don't work but I've left them in to sort of explain what I am trying to achieve.
1. Even though node-pty is connected to process.env, SOME_CONFIG isn't present. I don't know if that's because that's expected or because writes are returning instantly without doing anything.
2. I can't kill the process using `ptyProcess.kill()` because I don't actually know when the writes finish. So in essense I don't know how to kill the process without just sending in an `exit` command.

Any tips on how I can achieve this?

**Comment by Tyriar** [comment]
You're doing it the best way I know of if you need the same session. You could alternatively have a single bash session per command

**Comment by moltenice** [comment]
> You're doing it the best way I know of if you need the same session. You could alternatively have a single bash session per command

@Tyriar my solution doesn't actually work as I mentioned. 

Also, if I understand your alternative correctly, it also wouldn't work as the sourced variables from the shell file would be lost once a new bash session is made for the next command.

**Comment by jerch** [comment]
> I don't know how to just display the output to stdout. It outputs the bash commands themselves etc.

Thats normal PTY/TTY echo behavior. Note that a TTY is meant for interactive user session, most of the time echoing user input back is a wanted feature. You can control that by temporarily switching off echoing (see manpage of `stty`, e.g. `stty -echo`).

> All the writes are going through in one go. I think this is expected behaviour for a pty like this but doesn't help me achieve what I am trying to achieve.

Not sure what you mean here. There is a chance, that nodejs might buffer things and send them in one bigger chunk to the other side, yeah. Still it should not chance the runtime behavior of your scripts. (Bash reads STDIN in RAW mode, thus decides itself bytewise when and where a command ends, not by some magic chunk border). A TTY in RAW mode is on data level not much more than a OS pipe, it just pushes bytes forward.

> There is no way for me to check if a command ran or not. The `await`s I have don't work but I've left them in to sort of explain what I am trying to achieve.

I think you have here a misconception of a PTY in general. You cannot await a command to be finished that way. If you take a closer look you see, that you just write strings/bytes into a some sink. The PTY has no idea of the meaning of those data, thus no idea what to wait for. It is the process on the other side, that gives it a meaning (here `bash` where the data is forming commands that create subprocesses).
Maybe I misunderstood your goal with those awaits.

> Even though node-pty is connected to process.env, SOME_CONFIG isn't present. I don't know if that's because that's expected or because writes are returning instantly without doing anything.

It does not work that way. You bound the current `process.env` during `pty.spawn`, which creates a new process (`bash`) with these values. As soon as the process is up, it has its own context with either hard-copied or copy-on-write env vars, they have their own lifecycling in that process context. There is nothing connect to your original `process.env` anymore.
Fix: Set the custom env var before spawing the PTY.

> I can't kill the process using `ptyProcess.kill()` because I don't actually know when the writes finish. So in essense I don't know how to kill the process without just sending in an exit command.

There are several ways to get informed, when the shell in the PTY did its work:
- echo some sentinel when done, listen for that to appear in `pty.on('data', ...)`, then you can safely kill it
- or put a final script in your command list containing `exit` and call it with `source final_script`, this will automatically end `bash` and the PTY

**Comment by moltenice** [comment]
Thanks @jerch! That's really informative. And you're right, I have misunderstood how a PTY works (I am completely new to the concept).

I guess I am so used to just using a terminal manually and knowing when a command has finished just by waiting for the prompt to show up again, that perhaps programatically, I didn't realise this would be much harder.

In essence what I am trying to do is run these 3 commands in the same bash session one by one:

```shell
source ./config.sh
SOME_CONFIG="${SOME_CONFIG}bar"
./output.sh
```

As a human, I can type them into a terminal one by one, and wait the appropriate time for each command to finish before typing the next one.

I wanted to do something similar programatically. And more importantly take output from a command, do some computation on the Javascript side, and then use the output strings from that to write in more commands and again wait until the command finished running, all in the same spawned `bash` sub-session.

But this is not how PTY works as you've explained.

Thanks for your help @Tyriar and @jerch!

**Comment by jerch** [comment]
@moltenice If that 3-liner works correctly in your interactive terminal, it should also work in a PTY, e.g:
```javascript
var ptyProcess = await pty.spawn('bash', [], {
    name: 'xterm-color',
    cwd: process.cwd(),
    env: process.env,
});

ptyProcess.onData(function (data) {
    process.stdout.write(data);
});
ptyProcess.write('source ./config.sh\r');
ptyProcess.write('SOME_CONFIG="${SOME_CONFIG}bar"\r');
ptyProcess.write('./output.sh\r');
ptyProcess.write('exit\r');
```
The exit at the end will close the shell and thus the PTY, which you can track on javascript side with an event.

If you want to inject the custom env var on javascript side, you'd have to do that prehand:
```javascript
const customEnv = {...process.env};
customEnv.SOME_VAR = '....';
var ptyProcess = await pty.spawn(shell, [], {
    name: 'xterm-color',
    cwd: process.cwd(),
    env: customEnv,  // processes on PTY now inherit env with that custom var
});
```

**Comment by moltenice** [comment]
Would `customEnv` get updated with any changes the subprocess makes to it? In general if a subprocess modifies its env vars (sourced variables for example), can the parent JS process access this?

**Comment by jerch** [comment]
Nope, the env vars are copied over and have their own lifecycle at the other end. Inspecting them at runtime is only possible by explicitly outputting them (e.g. `echo $SOME_VAR`), or by more aggressive means, like hooking into the process with debugging flags. The process isolation is pretty strict in all OS we have, internal things cannot be accessed/modified that easy.

**Comment by moltenice** [comment]
Makes sense, cheers. 👍
