### ISSUE TITLE
How to convert output text into HTML

### ISSUE THREAD

**Issue by Employee87** [microsoft/node-pty#464]
## Environment details

- OS: Windows
- OS version: 10
- node-pty version: latest of march 7 2021

## Issue description

I'm using this https://github.com/microsoft/node-pty and this ansi-to-html doesn't work well with it, it works maybe 50%, but still leaves some invalid text left. Is there a function available to properly convert it to html code?

**Comment by jerch** [comment]
To my knowledge ansi-to-html only deals with a subset of possible escape sequences so yeah, it will not work with arbitrary PTY output.

To get better overall sequence support you gonna need a full emulator with some html output caps, e.g. [xterm.js](https://github.com/xtermjs/xterm.js) or [node-ansiterminal]() (the latter has some prepared shims for your use case [here](https://github.com/netzkolchose/node-ansiterminal/tree/master/examples#toolsjs)).
