### ISSUE TITLE
npm package and source code don’t match – 0.10.1 on npm but 0.10.0 on GitHub?

### ISSUE THREAD

**Issue by lydell** [microsoft/node-pty#470]
The latest version on npm is 0.10.1, but package.json in this repo says 0.10.0:

https://github.com/microsoft/node-pty/blob/771bd5744ee8a07817af823342d7a343bf63f516/package.json

Did you forget to push some commits?

(I downloaded both the 0.10.0 and the 0.10.1 tarballs and diffed them. This does not seem to be a malicious release.)

**Comment by Tyriar** [comment]
That was built off https://github.com/microsoft/node-pty/tree/node_v14 to backport a fix. All is well, we don't bump the release number normally as it triggers a release, it's harmless leaving it at 0.10.0 in main 🙂

**Comment by lydell** [comment]
Ah, thanks for clarifying!
