### ISSUE TITLE
Stop Forced Clear on .spawn()

### ISSUE THREAD

**Issue by SirTenzin** [microsoft/node-pty#483]
## Environment details

- OS: Windows 10 Home
- OS version: 19042.1110
- node-pty version: 0.10.1

## Issue description
I spawned a console using the basic README example, I was wondering how to stop a forced clear on spawn.

**Comment by Tyriar** [comment]
conpty may clear the screen, to avoid this you can set `conptyInheritCursor`:

https://github.com/microsoft/node-pty/blob/3794fb111c51f2fa03ee6150468cc462db76699a/typings/node-pty.d.ts#L98-L102
