### ISSUE TITLE
Use without forking

### ISSUE THREAD

**Issue by dustinlacewell** [microsoft/node-pty#484]
Is there anyway to use node-pty as a virtual terminal buffer of sorts?

I am trying to connect up https://github.com/vadimdemedes/ink a React renderer for the terminal, to telnet.

Ink takes in a NodeJS.ReadStream and a NodeJS.WriteStream which are usually stdin and stdout. I need stdin-like and stdout-like objects to that Ink can do its thing, but I can redirect data to and from telnet.

Wondering if this project would work for me.

**Comment by mofux** [comment]
Couldn't you just pass the telnet stream directly to Ink, without node-pty at all?

**Comment by dustinlacewell** [comment]
That... worked! <3
