### ISSUE TITLE
The system environment variables obtained are different

### ISSUE THREAD

**Issue by zhangbaojia** [microsoft/node-pty#488]
## Environment details

- OS: macOS
- OS version: 
- node-pty version: 0.10.1

## Issue description
I tried running electron in the example;

The source code to run:

![20210811150806](https://user-images.githubusercontent.com/19427334/128985274-230c79c6-381a-4655-91f5-f735179020fd.jpg)

Then it can be packaged and run（electron-builder）:

![20210811150759](https://user-images.githubusercontent.com/19427334/128985391-063c96dc-e5d2-44b1-b23f-f3d4c7950dc3.jpg)

The environment variables obtained above are surprisingly different.

**Comment by zhangbaojia** [comment]
![20210811163824](https://user-images.githubusercontent.com/19427334/128997830-c258a6b7-0def-4075-b482-a45a84627401.png)

now i know !

**Comment by zhangbaojia** [comment]
I have another problem:

I'm doing the same thing(source code to run and build to run), Encounter coding problems:

![20210811182409](https://user-images.githubusercontent.com/19427334/129013614-7b2e6cbc-73b9-43a1-9f3c-9b448fe2a571.jpg)
![20210811182416](https://user-images.githubusercontent.com/19427334/129013624-59d84ab3-f027-47e2-bf3b-60bc174432b6.jpg)

**Comment by Tyriar** [comment]
That's probably the `$LANG` environment variable? Diffing `env` in each terminal should help
