### ISSUE TITLE
How can I use PKG to package this module across platforms?

### ISSUE THREAD

**Issue by mycve** [microsoft/node-pty#494]
## Environment details

- OS:
- OS version:
- node-pty version:

## Issue description
How can I use PKG to package this module across platforms.
I hope to use it on as many platforms as possible. Some platforms may not have nodejs environment.

**Comment by Tyriar** [comment]
Not sure what pkg is 🤷‍♂️, doesn't seem like the right place for this question.

**Comment by mycve** [comment]
它是nodejs打包为可执行文件的一个模块。

> 不确定 pkg 是什么 🤷‍♂️, 似乎不是这个问题的正确位置。

It is a module that nodejs is packaged as an executable.
You can use it by executing  npm install -g pkg.
But usually I want to use node-pty on more platforms through cross compilation.

**Comment by Tyriar** [comment]
Yeah I don't know, I don't use it.
