### ISSUE TITLE
Can pty clear the previous data

### ISSUE THREAD

**Issue by Lee-42** [microsoft/node-pty#496]
## Environment details

- OS: Window
- OS version: 10
- node-pty version: 0.10.1

## Issue description
I tried to use pty.spawn to create a pty, and then use the socket connection on the front end to get the output of the pty and display it on Xterm.
The current phenomenon is that when I use another socket to connect to the pty, the data I get contains the data generated by the first socket operation pty.
Does the opened pty have an API to clear the cache?

**Comment by jerch** [comment]
Not sure what you are trying to achieve, it either sounds like you want to have multiple independent terminal connections (use multiple pty objects for that), or you want to multiplex a single terminal connection (then mirroring is the wanted behavior).

> Does the opened pty have an API to clear the cache?

Nope, there is no such cache that could be cleared. I suggest to read into TTY/PTY (posix) and ConPty (windows) semantics before trying to build more complex solutions.
