### ISSUE TITLE
Process HANDLE leak on windows

### ISSUE THREAD

**Issue by xhcoding** [microsoft/node-pty#513]
## Environment details

- OS:  Windows10
- OS version: 21H1 19043
- node-pty version: 0.10.1

## Issue description

```javascript
var os = require('os');
var pty = require('node-pty');

var shell = os.platform() === 'win32' ? 'powershell' : 'bash';


setInterval(() => {

  console.log("spawn new process");
  var ptyProcess = pty.spawn(shell, [], {
    name: 'xterm-color',
    cols: 80,
    rows: 30
  });

  ptyProcess.kill();


}, 5000);

```
After the above code runs for a few minutes :

<img width="262" alt="16390417046148" src="https://user-images.githubusercontent.com/30917129/145368882-190a390a-dffb-4ef6-a375-b134de21aebc.png">

**Comment by Tyriar** [comment]
Should be fixed in https://github.com/microsoft/node-pty/pull/510
