### ISSUE TITLE
Delay between stdout output and data event fired

### ISSUE THREAD

**Issue by justablob** [microsoft/node-pty#529]
## Environment details

- OS: Xubuntu
- OS version: 21.10
- node-pty version: 0.10.1

## Issue description
It seems like sometimes, there is a delay between the child writing to stdout and `IPty.onData` being fired. For reference: I observed this behavior while writing a libinput gestures client for Linux. Opening `libinput debug-events` in a normal terminal gave me immediate stdout output, while _sometimes_, the output from node-pty is lagging behind a few hundred milliseconds. It is miles better than `child_process` buffering, but still leads to noticeable delays.

**Comment by Tyriar** [comment]
I haven't observed this, I don't use Linux much these days though. Next steps here would be to try launching the node process in question with `--inspect`, connecting chromium and getting a performance profile to see if there was something else blocking the main thread:

![image](https://user-images.githubusercontent.com/2193314/155159488-4f429d63-8108-4908-8f91-dac7f99d8ecb.png)

**Comment by sedwards2009** [comment]
I upgraded the node-pty version I was using a month or two ago and there was a noticeable improvement in latency for plain interactive use.
