### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by childrentime** [microsoft/node-pty#531]
## Environment details

- OS: win
- OS version: 10
- node-pty version: ^0.10.1

## Issue description

when i use ts-node and typescript
```import pty from 'node-pty';```
```typescript
const term = pty.spawn(shell, ['--login'], {
    name: 'xterm-color',
    cols: 80,
    rows: 24,
    cwd: process.env.HOME,
});
```

it will throw error ```TypeError: Cannot read property 'spawn' of undefined';```

and when i change to ```const pty = require('node-pty');```

it works

**Comment by childrentime** [comment]
btw, window build tools seems to no need to install

**Comment by Tyriar** [comment]
@childrentime the build tools only need to be installed if you don't have the right tool chain installed.

You want `import * as pty from 'node-pty'`, that's the equivalent to `var pty = require('node-pty')` on the readme.

**Comment by childrentime** [comment]
node.js latest version has window build tools built in.
and what my point is, when i use import instead of require, it will throw runtime error

**Comment by childrentime** [comment]
Oooooh. My mistake. Thanks❤️❤️❤️!  I just used to default export😅.
