### ISSUE TITLE
node-pty does not install on Windows

### ISSUE THREAD

**Issue by MelvinG24** [microsoft/node-pty#536]
## Environment details

- OS: Windows
- OS version: 10
- node-pty version: 

## Issue description
PS C:\Users\melvi\source\repos> npm install --global --production windows-build-tools
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated windows-build-tools@5.2.2: Node.js now includes build tools for Windows. You probably no longer need this tool. See https://github.com/felixrieseberg/windows-build-tools for details.
[##################] \ reify:ajv: http fetch GET 200 https://registry.npmjs.org/ajv/-/ajv-6.12.6.tgz 1352ms (cache miss)

**Comment by daniel-brenot** [comment]
These are all warns. Please make sure first of all that your console output is formatted as a code block. Secondly, how is this failing? Also, your command there is to install production build tools for windows, not node-pty, so the console you posted seems completely unrelated to the issue.
