### ISSUE TITLE
why do we need resize?

### ISSUE THREAD

**Issue by makarhuyaker** [microsoft/node-pty#541]
## Environment details

- OS: Windows
- OS version: 10
- node-pty version:  0.10.1

**Comment by Tyriar** [comment]
You can read up about ptys here: https://man7.org/linux/man-pages/man7/pty.7.html, https://man7.org/linux/man-pages/man3/forkpty.3.html, https://man7.org/linux/man-pages/man7/signal.7.html (sigwinch is resize)
