### ISSUE TITLE
How to listen the finish event or state of a command execution?

### ISSUE THREAD

**Issue by mexhfl** [microsoft/node-pty#542]
## Environment details

- OS:Windows/Macos
- OS version:
- node-pty version:0.4.3

**Comment by Tyriar** [comment]
You can't without some form of shell integration (not an easy problem) or by running a one and done command like `bash -c "yourcommand"`

**Comment by deflexable** [comment]
can you explain more on how `bash -c "yourcommand"` enable you detect when a command execution has completed

**Comment by Tyriar** [comment]
@deflexable `spawn('bash')` will open an interactive bash shell, `spawn('bash', ['-c', 'yourcommand'])` will run `yourcommand` and then exit.
