### ISSUE TITLE
Cannot find module '../build/Debug/conpty.node'

### ISSUE THREAD

**Issue by kachbit** [microsoft/node-pty#544]
## Environment details

- OS: Windows
- OS version:
- node-pty version: 0.9.0

## Issue description
Package installs successfully. However, when electron window loads, the terminal does not display, and the console shows two errors:
`innerError Error: Cannot find module '../build/Debug/conpty.node'`
and
```
Uncaught Error: The module '...\node-pty\build\Release\conpty.node'
was compiled against a different Node.js version using NODE_MODULE_VERSION 93. This version of Node.js requires NODE_MODULE_VERSION 80. Please try re-compiling or re-installing the module (for instance, using `npm rebuild` or `npm install`).
```

**Comment by Tyriar** [comment]
This means you compiled node-pty against your system's node version, not electron's. See https://github.com/microsoft/node-pty/blob/main/examples/electron/npm_install.sh for an example of how to do this properly.

**Comment by kachbit** [comment]
Executing the .sh file still does not fix the problem :/

**Comment by kachbit** [comment]
@Tyriar 
Okay, I think I have it figured out. I need to download the correct node version that supports Node Module Version 80. I looked through [this](https://nodejs.org/en/download/releases/#ref-1) (page 11) to try to find the correct release, however, it does not contain a release with Node Module Version 80! Only 79 and 83. Sorry if this is annoying, but I'm stumped.

**Comment by Tyriar** [comment]
Here's the electron doc page on it http://man.hubwiz.com/docset/electron.docset/Contents/Resources/Documents/docs/tutorial/using-native-node-modules.html
