### ISSUE TITLE
How do I gracefully close the terminal? 

### ISSUE THREAD

**Issue by MassMessage** [microsoft/node-pty#549]
## Environment details

- OS: Windows 11
- OS version:Windows 11 Home Insider Preview Single Language
- node-pty version: 0.10.1

## Issue description

let's say I have a pseudo-terminal (using xterm.js) in my application, connect to a real-terminal (powershell) through node-pty.  the user happens to close it (it's inside a tab), so I need to "close" the terminal "connection" with powershell. What's the proper way to do this? call `kill()`? send `exit` to the terminal run? regard to cleaning resources, is there anything I do need to release?

**Comment by Tyriar** [comment]
`kill` is the way to do this currently, though there are issues on Windows with clean up that's tracked in an issue on microsoft/terminal

**Comment by sridhar562345** [comment]
@Tyriar 

But when I used kill, `.bash_history` file is not updated.
