### ISSUE TITLE
'ptyProcess.on' is deprecated

### ISSUE THREAD

**Issue by Seanmclem** [microsoft/node-pty#552]
## Environment details

- OS: Mac
- OS version: Latest
- node-pty version: 0.10.1

## Issue description
When enabling typescript for my node-pty usage - I am now seeing a waring that `'ptyProcess.on' is deprecated`. However, it suggests no alternative, and I see that syntax used in the README.. So is my editor wrong or are the docs outdated?

**Comment by Seanmclem** [comment]
Seems like the correct syntax is 
`ptyProcess.onData((data: any) => {`

rather than

`ptyProcess.on('data', function (data: any) {` 

Still, the README would need updated, no?

**Comment by Tyriar** [comment]
Yes, the readme is out of date atm 👍
