### ISSUE TITLE
using xterm.js, opening multiple electron windows, they all use the same node-pty instances and mirror themselves

### ISSUE THREAD

**Issue by FormalSnake** [microsoft/node-pty#556]
## Environment details

- OS: macOS
- OS version: 13.0
- node-pty version: 0.10.1

## Issue description
If you want the complete repository, it is named kaiium and can be found on my profile
It looks like this:

https://user-images.githubusercontent.com/90651091/185099191-03f57f74-6c9c-4d72-821e-54807993b15a.mov

.

**Comment by Tyriar** [comment]
See https://github.com/xtermjs/xterm.js/issues/4014#issuecomment-1219653147, this isn't a support forum and the issue is unrelated to both xterm.js and node-pty
