### ISSUE TITLE
question: supported nodejs versions

### ISSUE THREAD

**Issue by jjangga0214** [microsoft/node-pty#557]
Hi!

Thanks for this project :)

May I ask which nodejs versions `node-pty` supports?
(`node-pty`'s package.json does not have `engines` field.)

For example, I saw some (closed) issues saying like "node 17 is not supported", or "installation failed in node 15".

I want to use `node-pty` in my open-source project. 
But the project should support **every** recent nodejs versions.
(e.g. `node>=16` : 16.x, 17.x, 18.x, 19.x, 20.x)

What's more, once a new nodejs version is released(e.g. 21.x(future)), my package should become ready for the runtime as soon as possible.

Would it be possible?

Thanks!

**Comment by z3bra5hax** [comment]
This is silly. LTS (eg 16.x, 18.x, 20.x) within a reasonable timeframe of their release is a fair request/assumption as long as this is considered an active project however attempting to support every release in between would slow down bug resolution and development too much. This is non-revenue-generating project for Microsoft so let's dial down our expectations on bleeding edge releases...

**Comment by jjangga0214** [comment]
@z3bra5hax Then does `node-pty` support every nodejs LTS?
For future LTS (e.g. 22.x), once the new LTS releases, how rapidly would `node-pty` start supporting it?

Thanks.

**Comment by daniel-brenot** [comment]
> @z3bra5hax Then does `node-pty` support every nodejs LTS currently? For future LTS (e.g. 22.x), once the new LTS releases, how rapidly would `node-pty` start supporting it?
> 
> Thanks.

The project will support LTS when it is updated to do so. This project isn't specifically a high priority from microsofts perspective I imagine, so it relies on FOSS developers to add support for LTS versions. I am currently working on support, but there is no specific date for when that may be done(could be a month, could be years).

**Comment by kkocdko** [comment]
The #644 will make this project support from node 16 to 21, you can download & replace to test, see the message in that PR.

**Comment by banekondic1996** [comment]
For God sake Microsoft, why can't this node-pty work. Whatever version of nodejs i use i get version mismatch
