### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by janek515** [microsoft/node-pty#558]
## Environment details

- OS: Windows 11
- OS version: 22622.575
- node-pty version: 0.10.1

## Issue description

When installing (using yarn) a build error appears
```
# This file contains the result of Yarn building a package (node-pty@npm:0.10.1)
# Script name: install

[31m[1mUsage Error[22m[39m: Couldn't find a script name "node-gyp" in the top-level (used by node-pty@npm:0.10.1). This typically happens because some package depends on "node-gyp" to build itself, but didn't list it in their dependencies. To fix that, please run "yarn add node-gyp" into your top-level workspace. You also can open an issue on the repository of the specified package to suggest them to use an optional peer dependency.

[1m$ [22myarn run [--inspect] [--inspect-brk] [-T,--top-level] [-B,--binaries-only] <scriptName> ...
```

Running `yarn add node-gyp` fixes the problem

**Comment by UPL123** [comment]
I think you need to install `node-gyp`. You can install it using

```bash
yarn add node-gyp
```

**Comment by daniel-brenot** [comment]
Can we close this? The answer was given.

**Comment by janek515** [comment]
The point is you shouldn't need to install it manually

**Comment by daniel-brenot** [comment]
> The point is you shouldn't need to install it manually

Then this most likeley should have node-pty added to the peer dependencies.

**Comment by Tyriar** [comment]
This is already called out in the readme that you need to install some build tools on Windows: https://github.com/microsoft/node-pty#windows
