### ISSUE TITLE
Electron example: does not work with v20

### ISSUE THREAD

**Issue by codestitch** [microsoft/node-pty#561]
## Environment details

- OS: windows
- OS version: 11
- node-pty version: 0.10.1
- electron: 20.1.4
- xterm: 4.2.0
- electron-rebuild: 3.2.9

## Issue description

Tried building from the example (node-pty/examples/electron). It worked! 
However, when upgrading electron and other libs would wouldn't work.

**./npm-install.sh**

```
# Electron's version.
export npm_config_target=20.1.4
# The architecture of Electron, can be ia32 or x64.
export npm_config_arch=x64
export npm_config_target_arch=x64
# Download headers for Electron.
export npm_config_disturl=https://www.electronjs.org/headers
# Tell node-pre-gyp that we are building for Electron.
export npm_config_runtime=electron
# Tell node-pre-gyp to build module from source code.
export npm_config_build_from_source=true
# Install all dependencies, and store cache to ~/.electron-gyp.
HOME=~/.electron-gyp npm install
```

**package.json**

```
{
  "name": "node-pty-electron-example",
  "version": "1.0.0",
  "description": "A minimal node-pty Electron example",
  "main": "main.js",
  "scripts": {
    "start": "electron . --ignore-gpu-blacklist",
    "rebuild": "electron-rebuild node-pty"
  },
  "repository": "https://github.com/Tyriar/node-pty",
  "author": "Tyriar",
  "dependencies": {
    "electron": "^20.1.4",
    "node-pty": "^0.10.1",
    "xterm": "4.2.0"
  },
  "devDependencies": {
    "electron-rebuild": "^3.2.9"
  }
}
```

When running: `npm start` the terminal doesn't appear.

When rebuilding: `npm rebuild`

![image](https://user-images.githubusercontent.com/5573444/190393559-b756dc7a-5293-4dbe-b092-1734153c39d4.png)

Will appreciate your help.

Thank you

**Comment by z3bra5hax** [comment]
@codestitch [this](https://stackoverflow.com/questions/63627716/nodejs-electron-forge-node-gyp-could-not-find-any-visual-studio-installation-to) might be of some help.

**Comment by codestitch** [comment]
thank you @z3bra5hax

**Comment by daniel-brenot** [comment]
@codestitch Can this be closed then? If so, please close this issue.
