### ISSUE TITLE
Set HOME path while executing cd command

### ISSUE THREAD

**Issue by vidhimultiqos** [microsoft/node-pty#562]
## Environment details

- OS: Ubuntu
- OS version: 20.04
- node-pty version: 0.10.1

## Issue description
How to Set HOME path while executing cd command

**Comment by daniel-brenot** [comment]
Please give more of a description to this issue. You haven't really given any context here that anyone can help you with.

**Comment by vidhimultiqos** [comment]
![image](https://user-images.githubusercontent.com/75296188/201645468-71359cb7-311f-4c4a-964d-25fd68263055.png)

While I am running the "cd" command in a web-based terminal, it returns me the "HOME path is not set"

**Comment by Tyriar** [comment]
This is an issue on your end, looks like somehow you created the shell without $HOME set (or it was unset)
