### ISSUE TITLE
macos repeated cammand in onData callback

### ISSUE THREAD

**Issue by xpf0000** [microsoft/node-pty#565]
## Environment details

- OS: MacOS
- OS version: 12.3 Apple M1
- node-pty version: 0.10.1
- electron: 16.2.8
- pty:  this.pty = Pty.spawn(process.env['SHELL'], [], {
      name: 'xterm-color',
      cols: 80,
      rows: 34,
      cwd: process.cwd(),
      env: process.env,
      encoding: 'utf8'
    })

## Issue description
repeated cammand in onData callback,  example cammand is 'ls -al', onData callback first output 'ls -al', then output the right data

**Comment by Tyriar** [comment]
The shell/pty may echo back the command, this is out of scope of node-pty
