### ISSUE TITLE
node-pty process is not kill

### ISSUE THREAD

**Issue by vidhimultiqos** [microsoft/node-pty#568]
## Environment details

- OS: Linux
- OS version: 22.02
- node-pty version: "^0.10.1"
- electron: "^19.0.11"
-  xterm: "^5.0.0"

## Issue description
While I am killing a session of node-pty, it is not killing. All data appear in the next tab which is opened.
Before:
![image](https://user-images.githubusercontent.com/75296188/202634047-de1113e1-6bb5-4026-ac44-26aa5d7c8e7b.png)
![image](https://user-images.githubusercontent.com/75296188/202634103-b9475c0e-bda8-4c3c-9094-71f95dce5ccd.png)

After:
Closing First tab:
![image](https://user-images.githubusercontent.com/75296188/202634164-f5c98160-2499-4e06-8b98-d645bc89ef93.png)

Data are rending in the second tab automatically. 

```
process.kill(ptyProcess.pid)

or

ptyProcess.kill()
```

Above both syntax are not working

**Comment by Tyriar** [comment]
I'm not sure what I'm looking at in the screenshots, is there meant to be a shell process I'm not seeing?
