### ISSUE TITLE
`\x7f` is always converted to `\x08`/`\b` on Windows

### ISSUE THREAD

**Issue by connorskees** [microsoft/node-pty#575]
## Environment details

- OS: Windows 10
- OS version: `Microsoft Windows [Version 10.0.19045.2364]`
- node-pty version: `main` branch and `0.10.0`

## Issue description

When writing `\x7f` on Windows, the input will always be converted to `\x08`. It is unclear where this transform is occurring. To reproduce,

```ts
// relative to examples/fork/index.js
const pty = require('../..');

// reproduces with both cmd.exe and powershell.exe
const ptyProcess = pty.spawn('cmd.exe', [], {
  name: '...',
  cols: 80,
  rows: 26,
  cwd: process.env.USERPROFILE,
  // reproduces regardless of this value
  useConpty: true,
});

ptyProcess.onData(data => process.stdout.write(data));

ptyProcess.write('python -c "import msvcrt; print(msvcrt.getch())"\r');
ptyProcess.write('\x7f');

process.on('exit', () => ptyProcess.kill());
setTimeout(() => process.exit(), 500);
```

![image](https://user-images.githubusercontent.com/39542938/210917499-980e29eb-bf6b-485c-abcf-1ea7a0c0a2dc.png)

This issue appears to be independent of the shell and is reproducible using both winpty and conpty.

**Comment by Tyriar** [comment]
It would be happening by conpty (https://github.com/microsoft/terminal) or cmd
