### ISSUE TITLE
Installation Error : npm ERR! g++: error：unrecognized command line option ‘-std=gnu++14’

### ISSUE THREAD

**Issue by zhangbaojia** [microsoft/node-pty#593]
## Environment details

- OS:   `Linux version 3.10.0-862.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-28) (GCC) ) #1 SMP Fri Apr 20 16:44:24 UTC 2018`
- Nodejs version: 16.20.0
- npm version: 8.19.4
- Python version: python:3.10.10
- node-pty version:  0.10.1
- make version 3.82
- gcc version 4.8.5

## Issue description

> sudo npm i node-pty

npm ERR! code 1
npm ERR! path /home/abat/src/abat/nodejs/node_modules/node-pty
npm ERR! command failed
npm ERR! command sh -c -- node scripts/install.js
npm ERR! make: enter the directory“/home/abat/src/abat/nodejs/node_modules/node-pty/build”
npm ERR!   CXX(target) Release/obj.target/pty/src/unix/pty.o
npm ERR! make: out of directory“/home/abat/src/abat/nodejs/node_modules/node-pty/build”
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.1.0
npm ERR! gyp info using node@16.20.0 | linux | x64
npm ERR! gyp info find Python using Python version 3.10.10 found at "/usr/bin/python3.10/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3.10/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/resource/node-v16.20.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/abat/src/abat/nodejs/node_modules/node-pty/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/resource/node-v16.20.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/abat/.cache/node-gyp/16.20.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/abat/.cache/node-gyp/16.20.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/resource/node-v16.20.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/abat/.cache/node-gyp/16.20.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/abat/src/abat/nodejs/node_modules/node-pty',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! g++: error：unrecognized command line option ‘-std=gnu++14’
npm ERR! make: *** [Release/obj.target/pty/src/unix/pty.o] error 1
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/resource/node-v16.20.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:201:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
npm ERR! gyp ERR! System Linux 3.10.0-862.el7.x86_64
npm ERR! gyp ERR! command "/usr/resource/node-v16.20.0-linux-x64/bin/node" "/usr/resource/node-v16.20.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /home/abat/src/abat/nodejs/node_modules/node-pty
npm ERR! gyp ERR! node -v v16.20.0
npm ERR! gyp ERR! node-gyp -v v9.1.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/abat/.npm/_logs/2023-04-17T06_22_32_444Z-debug-0.log

**Comment by deepak1556** [comment]
GCC version is not sufficient to support gnu++14, please update to GCC > 6 and try again. Thanks!
