### ISSUE TITLE
Error while connecting to node-pty

### ISSUE THREAD

**Issue by as2r9** [microsoft/node-pty#594]
## Environment details

- OS: MacOS
- OS version: Ventura 13.2
- node-pty version: 0.10.1
- processor - M1 chip

## Issue description
I installed the node-pty using 
`npm install node-pty`
after this when i try to run my code to connect to the terminal i am getting this error
`
(mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
`

Can I know how I can solve this Issue.

**Comment by Tyriar** [comment]
You'll need to look up how to install npm modules for different architectutes separately. I'm not sure how to do it
