### ISSUE TITLE
new stable release

### ISSUE THREAD

**Issue by SimonSiefke** [microsoft/node-pty#596]
## Issue description

The latest version 0.10.1 on npm was published ~2 years ago. Since then a lot of great changes have happened, most importantly support for node 15,16,17,18,19,20. 
Unfortunately by default when installing node-pty the latest version 0.10.1 is installed which does not work with node 15,16,17,18,19,20.

I might be wrong, but I believe the 0.11.0-beta* versions are working well and could be used for a new stable release.

**Comment by Tyriar** [comment]
I'll make a note to hopefully get this done next month 👍
