### ISSUE TITLE
Uncaught Exception: winpty-conout-... at PipeConnectWrap.afterConnect

### ISSUE THREAD

**Issue by JaryGuo** [microsoft/node-pty#598]
## Environment details

- OS: Win11
- OS version: 60??
- node-pty version: 0.10

today I encounter the exception:
```
Uncaught Exception:
Error: connect ENOENT
winpty-conout-....
at PipeConnectWrap.afterConnect [as oncomplete] (netjs:1146:16)
```

and i try to debug the code in WindowsPtyAgent and finaly found that 
```
this._useConpty = this._getWindowsBuildNumber() >= 18309;
```
is not correct for win11, which log out the version 60?? (sorry i debug in other colleague‘s computer)

and currently i just modified the code to `this._useConpty = true;` as in my teams, all computer os should be newer than 18309..

**Comment by Tyriar** [comment]
You're saying `_getWindowsBuildNumber()` is returning 60? I've never seen this, here's what is run, can you try debug it to see where 60 comes from?

https://github.com/microsoft/node-pty/blob/ae441595fbe59ebceb742cfb5bde5844b6c99626/src/windowsPtyAgent.ts#L213-L218

**Comment by JaryGuo** [comment]
> 

i debug the electron app today, and the os.release() print out "6.0.6002"

it's weird. and i log out the os.release() in the node.js console, the result is "10.0.22621".

**Comment by JaryGuo** [comment]
it seems to be the bug of nodejs

https://github.com/nodejs/node-v0.x-archive/issues/25896

**Comment by ZHUMINGZHE123** [comment]
Has this bug been fixed? I had the same problem:
uncaughtException error:  Error: connect ENOENT\\.\pipe\winpty-conout-18516-2-1db58d6771840bb-a2b6b307cb7ea97e6c1568b3f58e3aec
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'connect',
  address: '\\\\.\\pipe\\winpty-conout-18516-2-1db58d6771840bb-a2b6b307cb7ea97e6c1568b3f58e3aec'
}
