### ISSUE TITLE
Compiler warning about destructor

### ISSUE THREAD

**Issue by rzhao271** [microsoft/node-pty#607]
## Environment details

- OS: Windows
- OS version: 11
- node-pty version: latest main

## Issue description

1. Run `yarn`
2. See the following warning:

```
<some-path>\node-pty\deps\winpty\src\agent\Agent.cc(231): warning C4722: 'Age
nt::~Agent': destructor never returns, potential memory leak [C:\Users\raymondzhao\work\native-modules\nod 
e-pty\build\deps\winpty\src\winpty-agent.vcxproj]
```

**Comment by Tyriar** [comment]
I personally wouldn't touch the winpty codebase unless there's an important security issue. It's legacy and is typically not used/discouraged on modern Windows 11.

**Comment by rzhao271** [comment]
Closing for now
