### ISSUE TITLE
Published Release Notes

### ISSUE THREAD

**Issue by bradzacher** [microsoft/node-pty#609]
Is there any possibility of having published release notes for each release?
Right now there's nothing - no GH release, no `CHANGELOG.md` - not even a tag to denote the commit that was published to npm.

Without any notes it's really difficult to evaluate a release to tell what's changed!
The last tag is `0.10.0` - but it looks like there has been `0.10.1` and `1.0.0` since then

**Comment by eaviles** [comment]
+1, I noticed the v1 release and came here to look at the changes but found no notes.

**Comment by Tyriar** [comment]
I plan on getting to this in the next few days

**Comment by Tyriar** [comment]
Published: https://github.com/microsoft/node-pty/releases/tag/1.0.0
