### ISSUE TITLE
 Cannot find module '../build/Debug/conpty.node'

### ISSUE THREAD

**Issue by wcn007** [microsoft/node-pty#610]
## Environment details

- OS:Windows
- OS version:11
- node-pty version: 1.0.0
- node version: 16.16.0
- node-gyp: 7.1.2
- node-sass:7.0.0

## Issue description
![image](https://github.com/microsoft/node-pty/assets/22412746/5b354470-c1e2-4384-8fef-038c3c247b77)

**Comment by 2630025190** [comment]
解决了吗？

**Comment by Tyriar** [comment]
This means the install wasn't successful, re-install and review the error

**Comment by wcn007** [comment]
> 
Finally, manually compile dependencies using node gyp
