### ISSUE TITLE
Possibility to use raw mode ?

### ISSUE THREAD

**Issue by Et7f3** [microsoft/node-pty#650]
## Environment details

- OS: Linux
- OS version: 5.15.0-82-generic
- node-pty version: v1.0.0

## Issue description

I don't see argument to change initial mode of pty (I have to resort to spawn stty and change the value after pty creation).

What I look for is [stty_init](https://linux.die.net/man/1/expect) in GNU Expect. I am particularly interested in canonical mode and disabling utf8 output conversion (I see the setting for input encoding).

My need is that I want to transform a pty in cooked mode in raw mode so it become like a pipe.

**Comment by Et7f3** [comment]
Sorry for necromancing an old issue but I seem to have a working solution for [both windows](https://learn.microsoft.com/en-us/windows/console/setconsolemode) and one for linux. I have a quick n dirty solution so I don't think I will try to fix it. However it might merit good first issue or hacktoberfest tag.

**Comment by Tyriar** [comment]
Closing as out of scope, I think there are other npm modules that let you tweak these modes to accomplish what you're after.
