### ISSUE TITLE
Problem with binding.gyp file

### ISSUE THREAD

**Issue by legendSabbir** [microsoft/node-pty#665]
## Environment details

- OS: Android
- OS version: 
- node-pty version: 1.0.0
- Terminal apk name: Termux 
## Issue description

Error while installing . Tried in many devices still same issue . Before it used to work . Stopped working recently .  

`gyp: Undefined variable android_ndk_path in binding.gyp while trying to load binding.gyp`

![IMG_20240224_191405_777](https://github.com/microsoft/node-pty/assets/123853512/27543298-35f3-4118-b84b-956bb86dc6c5)

**Comment by bajrangCoder** [comment]
Yes, facing same issue.
And this issue started after recent node update (and also maybe due to node-gyp@10 version)

Tried some solution from internet but that doesn't work.

**Comment by Tyriar** [comment]
You're trying to install on Android? I wasn't aware this ever worked

**Comment by bajrangCoder** [comment]
> You're trying to install on Android? I wasn't aware this ever worked

Previously it used to work.
Problem is it needs a `"android_ndk_path"`  variable, but internally there is no need of this, if we will pass an empty android_ndk_path, but explicitly in _node-gyp_ `configure.js `

Check out this 👉 https://github.com/termux/termux-app/issues/3858#issuecomment-1963009340

**Comment by deepak1556** [comment]
We are not configuring the mentioned variable in our [binding.gyp](https://github.com/microsoft/node-pty/blob/main/binding.gyp), please confirm where the variable is being injected from and try to address it there.
