### ISSUE TITLE
[bug] posix_spawnp failed after calling spawn multiple times

### ISSUE THREAD

**Issue by fadezak100** [microsoft/node-pty#670]
## Environment details

- OS: macOs
- OS version:  12.0
- node-pty version: 1.0.0

## Issue description

I randomly get this error when calling `spawn` function multiple consecutive times:
```
/node_modules/node-pty/src/unixTerminal.ts:114
    const term = pty.fork(file, args, parsedEnv, cwd, this._cols, this._rows, uid, gid, (encoding === 'utf8'), helperPath, onexit);
                     ^
Error: posix_spawnp failed.
```

Here's a script to reproduce the problem.
```ts
import { spawn } from "node-pty"

const reproduce = async () => {
    for(let i = 0; i <= 1000; i++) {
        console.log(`the error is in ${i} iteration`)
        await spawn(`echo hello ${i}`, [], {
            name: 'xterm-color',
            cols: 80,
            rows: 30,
            cwd: process.env.HOME,
            env: process.env as any,
        })
    }
}

try {
    reproduce()
} catch (error) {
    console.error(error)
}

```

**Comment by Tyriar** [comment]
My guess is you're hitting some OS limit. Also `spawn` does not return a promise, so you could be hitting async issues.

As the example stands, I expect this to fail if you're trying to create 1000, so I'm closing this as out of scope. Please feel free to create a new issue if this happens with relatively few terminals.
