### ISSUE TITLE
Assertion in conpty.cc Line 110 when exiting VS Code

### ISSUE THREAD

**Issue by shanselman** [microsoft/node-pty#671]
## Environment details

- OS: WIndows w
- OS version: 26058.1400
- node-pty version: not sure how to check. Feb 28 is the date on the files?

## Issue description

When exiting visual studio code on windows I now get a single system bell a quick flash of an error message. 

It's so fast I had to do screen recording to capture the single frame!

![image](https://github.com/microsoft/node-pty/assets/2892/5c689ddf-de46-4c96-89ed-12e3a2f4d710)

Assertion Failed
File: node-pty\src\win\conpty.cc 
Line:110
Expression: status == napi_ok

**Comment by shanselman** [comment]
@deepak1556 @Tyriar interesting stuff here!

**Comment by deepak1556** [comment]
Thanks for the report, I am able to repro the issue.
