### ISSUE TITLE
ptyProcess.kill() is error

### ISSUE THREAD

**Issue by zhangbaojia** [microsoft/node-pty#690]
## Environment details

- OS: Windows11
- OS version: 11
- node-pty version: version: 1.0.0
- nodejs version: 20.14.0
- visual studio: 2022

## Issue description
![240626172010](https://github.com/microsoft/node-pty/assets/19427334/11063509-cba4-494d-963d-61f39bf454b8)

**Comment by zhanghu12138** [comment]
Have you found a solution？

**Comment by zhangbaojia** [comment]
这个只能是node-pty支持人员给修改，因为在其它系统没问题的。只有windows不行，如果是低版本node和低版本vs是没有这个问题的。
