### ISSUE TITLE
node-pty can't build with vs2022

### ISSUE THREAD

**Issue by YeesterPlus** [microsoft/node-pty#691]
## Environment details

- OS: windows NT
- OS version: 10 22H2 19045.4598
- VS version: 2022, 17.10.3
- SDKs: insider SDK, Win10/11 SDK

## Issue description

VSSDK for windows NT 10 fails
logs:
https://github.com/YeesterPlus/Assets/blob/main/issues/error%20wbt
https://github.com/YeesterPlus/Assets/blob/main/issues/error%20pty

**Comment by purp0w** [comment]
I also had the same error trying to install node-pty@latest, but when I tried to install the version that VSCode uses, which is a beta version using node-pty@beta, it worked for me.

**Comment by YeesterPlus** [comment]
OK ;)

**Comment by nedngo** [comment]
> I also had the same error trying to install node-pty@latest, but when I tried to install the version that VSCode uses, which is a beta version using node-pty@beta, it worked for me.

working
