### ISSUE TITLE
Wrong Node Module Version

### ISSUE THREAD

**Issue by ibaraki-douji** [microsoft/node-pty#693]
## Environment details

- OS: Ubuntu
- OS version: 22.04
- node-pty version: 1.0.0

## Issue description

After installing node-pty, i tried to spawn a command and this error triggered.
![image](https://github.com/microsoft/node-pty/assets/72337875/1bc370e0-65c5-4e29-a919-69136a3dbd04)

As proposed i tried `npm rebuild` and `npm install` but with no success

**Comment by nkfyz** [comment]
+1

**Comment by navid-m** [comment]
Same problem on Windows 11 (23H2) with the same node-pty version. Recompiling/reinstalling the module, or downgrading to various node and electron versions does not resolve the issue either. Is there any plan to address this?

**Comment by Tyriar** [comment]
This happens typically when you've installed/compiled node-pty using your local node's version and then try to run it in Electron. I'm not sure if this is still the right way to do it, but that's what this file does:

https://github.com/microsoft/node-pty/blob/main/examples/electron/npm_install.sh

Please consult Electron or your platform's docs on this.
