### ISSUE TITLE
[conpty error] Uncaught Exception:Error: read EP|PEat Pipe.onStreamRead (node:internal/stream base commons:218:20)

### ISSUE THREAD

**Issue by ruinb0w** [microsoft/node-pty#706]
## Environment details

- OS: windows11
- OS version: 22631.3880
- node-pty version: 1.0.0

## Issue description
If I set `useconpty=true` then I do `pty.kill()`, it will get an error `Uncaught Exception:Error: read EP|PEat Pipe.onStreamRead (node:internal/stream base commons:218:20)`
then I try to set `useconpty=false`, the xtermjs can't get title from node-pty.

How can I fix it?

**Comment by arthurdevv** [comment]
Have you found a solution？

**Comment by ruinb0w** [comment]
> Have you found a solution？

no, I'm using `pty.pause()` to pause client

**Comment by arthurdevv** [comment]
I implemented a workaround to prevent this error by using:

`process.kill(pty.pid)`

It looks like it has the same effect as `pty.kill()`

**Comment by Tyriar** [comment]
Not sure what's going on here, but it looks like it might be a problem with conpty. You could try with the new `useConptyDll` setting (https://github.com/microsoft/node-pty/issues/490), other than that you'd need to look into the code and see why it's failing or provide a small repro case.
