### ISSUE TITLE
Build failure caused by ts type error

### ISSUE THREAD

**Issue by ZWQ652** [microsoft/node-pty#729]
My electron project uses node py and has been able to build normally before. But now suddenly I can't build it anymore, every time it's an error in the ts type. What is the reason? Here are the logs:
![Image](https://github.com/user-attachments/assets/047e231f-b7c0-4365-b8b1-0dcb8a03d597)
![Image](https://github.com/user-attachments/assets/32e9c9b7-2441-41db-8bff-8243d2924d4d)

**Comment by Tyriar** [comment]
I'm not 100% sure what this is but node 16 is end of life so you could try update to 20+ to see if that fixes the problem.

**Comment by ZWQ652** [comment]
> I'm not 100% sure what this is but node 16 is end of life so you could try update to 20+ to see if that fixes the problem.我不是100%确定这是什么，但node 16是生命的终结，所以你可以尝试更新到20，看看是否解决了问题。

![Image](https://github.com/user-attachments/assets/5b4e0c85-b84e-48c6-9c58-bde1856ee8d0)
No, I have the same TS error when using all versions of the node

**Comment by ZWQ652** [comment]
Okay, I changed the package manager and reinstalled the dependencies. It can now be packed normally
