### ISSUE TITLE
Crash on Windows

### ISSUE THREAD

**Issue by eamodio** [microsoft/node-pty#746]
I keep (3 times in the last hour) getting the following crash when debugging:

![image](https://github.com/microsoft/node-pty/assets/641685/361fa12c-e592-4c6d-bcc7-a3e9f344fcb5)

I haven't seen this before but I'm guessing it is related either the latest insiders or my recent windows upgrade, or a combination of the two.

```
Version: 1.87.0-insider
Commit: 00124e9e5830e3efc897db71c781899f8a676295
Date: 2024-02-16T16:33:57.085Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Code-Insiders/1.87.0-insider Chrome/118.0.5993.159 Electron/27.3.2 Safari/537.36
```

```
Edition	Windows 11 Pro
Version	24H2
Installed on	‎2/‎15/‎2024
OS build	26058.1100
Experience	Windows Feature Experience Pack 1000.26058.1100.0
```

/cc @Tyriar @deepak1556

**Comment by deepak1556** [comment]
merging to https://github.com/microsoft/node-pty/issues/671

**Comment by Kitenite** [comment]
@deepak1556 , seeing this issue in an electron app on `^1.1.0-beta22`. Would you recommend downgrading to `1.1.0` or upgrading the `1.1.0-beta29`?

```
"electron": "34.2.0",
 "node-pty": "^1.1.0-beta22",
```

**Comment by deepak1556** [comment]
Please check if the issue repros with latest release `1.1.0-beta30`

**Comment by Kitenite** [comment]
This seems to work. Thanks @deepak1556 !
