### ISSUE TITLE
Fatal error: `pty.h` file not found

### ISSUE THREAD

**Issue by T-vK** [Microsoft/node-pty#79]
I always get an error while the installation script is running. It says `Fatal error: pty.h file not found`.   
I'm not sure what to make out of that. I tried to install libutil, but it was already installed (v0.2 btw).  
I'm on Linux, well Android, to be more accurate. Do I just need a pty.h file or is the fact that this file is missing implying a deeper issue?

**Comment by Tyriar** [comment]
I don't think it will work on Android

**Comment by Tyriar** [comment]
@T-vK I've never tried, it's not supported regardless though.

**Comment by T-vK** [comment]
But it says in the README that Linux is supported. What exactly do you mean by that then?
